# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""Bookstore API v2, as a server to implement.

A worked example exercising every construct the tree carries — including **Markdown** in a description, which is what the RAML spec says every `description:` is. See [Getting started](#) for the `{tenant}` you will need.

Generated from a RAML 1.0 definition. Subclass `Api`, implement every method,
and hand it to `create_app`:

    from bookstore_server import Api, create_app

    class Implementation(Api):
        ...

    app = create_app(Implementation())

`impl.py`, beside this package, is that file with every method stubbed. Copy it
out and fill it in -- regenerating rewrites this package and will not touch it.
"""

from __future__ import annotations

from .api import Api, create_router
from .app import create_app
from .runtime import Credential, SchemeSpec

__all__ = ['Api', 'Credential', 'SchemeSpec', 'create_app', 'create_router']
