# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""The application, over one implementation of `Api`."""

from __future__ import annotations

from typing import Any

from fastapi import FastAPI

from .api import Api, create_router

__all__ = ['create_app']

TITLE = 'Bookstore API'
VERSION = 'v2'
BASE_URI = 'https://{tenant}.books.example.com/{version}'
"""The `baseUri:` the document states.

Left as written, tokens and all. What `{tenant}` stands for is the deployment's
to decide, and a placeholder would be a value the document does not give.
"""


def create_app(implementation: Api, **options: Any) -> FastAPI:
    """A `FastAPI` application serving `implementation`.

    `options` go to `FastAPI(...)` unchanged, for anything the document does not
    state -- middleware, a `root_path`, a lifespan.
    """
    application = FastAPI(
        title=TITLE,
        version=VERSION,
        description='A worked example exercising every construct the tree carries — including **Markdown** in a description, which is what the RAML spec says every `description:` is. See [Getting started](#) for the `{tenant}` you will need.',
        **options,
    )
    application.include_router(create_router(implementation))
    return application
