# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""Every operation this API documents, as one interface.

    from bookstore_server import Api, create_app

    class Implementation(Api):
        ...

    app = create_app(Implementation())

`Api` inherits one abstract class per path group. `abc` refuses to construct a
subclass that has left a method out, so an operation the document describes and
the implementation does not is an error at startup rather than a 500 later.
"""

from __future__ import annotations

from fastapi import APIRouter

from . import books, deliveries, publications, search, shelves

__all__ = ['Api', 'create_router']


class Api(books.BooksApi, shelves.ShelvesApi, deliveries.DeliveriesApi, publications.PublicationsApi, search.SearchApi):
    """The whole document, as the methods to implement.

    One class per path group, joined here so that one object answers all of
    them. Implement each group separately by subclassing its own class under
    `api/` instead.
    """


def create_router(implementation: Api) -> APIRouter:
    """One router over every group, in the order the document declares them."""
    api = APIRouter()
    api.include_router(books.router(implementation))
    api.include_router(shelves.router(implementation))
    api.include_router(deliveries.router(implementation))
    api.include_router(publications.router(implementation))
    api.include_router(search.router(implementation))
    return api
