"""Turn a plan and a set of templates into a FastAPI server.

Two things differ from the `python-httpx` target, and both follow from what a server
is.

**A declaration is built here, not in a template.** An attribute carries a type,
maybe an alias, maybe a default; a route parameter carries all of that plus
where FastAPI reads it from. Assembling those in jinja would be four nested
conditions per line. They are strings, so they are built in Python and the
template joins them.

**The runtime is copied**, as the client's is: `runtime/runtime.py` arrives in
the generated package byte for byte, so the suite can run it and a reader can
read it.
"""

from __future__ import annotations

import pathlib
import re
from dataclasses import dataclass
from typing import TYPE_CHECKING, Final

import jinja2

from ....naming import class_name
from ....targets import Generated, Settings
from ..shared import docs
from ..shared.imports import Needs, Source, imports_for
from .plan import plan_server

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from ....reader import Tree
    from ..shared.annotate import Annotation
    from ..shared.imports import Imports
    from ..shared.plan import Argument, Case, Endpoint, Field, Model, Package

__all__ = ['generate_fastapi']

_HERE = pathlib.Path(__file__).resolve().parent
_TEMPLATES = _HERE / 'templates'
_RUNTIME = _HERE / 'runtime'

HEADER = '# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.'


@dataclass(frozen=True, slots=True)
class Parameter:
    """One parameter or attribute, as it is written in generated source."""

    name: str
    annotation: str
    #: The source of its default, or `None` where it has none and is required.
    default: str | None = None
    docs: str = ''
    #: The type with no constraint wrapped round it, for the line documenting
    #: it. `Annotated[str, Field(pattern=...)]` is what the route needs; `str`
    #: is what an `Args:` entry should say.
    bare: str = ''

    @property
    def documented(self) -> str:
        return self.bare or self.annotation

    @property
    def source(self) -> str:
        return f'{self.name}: {self.annotation}' + (f' = {self.default}' if self.default is not None else '')

    @property
    def required(self) -> bool:
        return self.default is None


def generate_fastapi(tree: Tree, settings: Settings) -> Generated:
    """The whole package, as paths to text."""
    package = plan_server(tree, settings)
    environment = _environment()
    files: dict[str, str] = {}
    root = package.module

    files[f'{root}/__init__.py'] = environment.get_template('package_init.py.jinja').render(
        header=HEADER, package=package
    )
    files[f'{root}/py.typed'] = ''
    files[f'{root}/runtime.py'] = f'{HEADER}\n{(_RUNTIME / "runtime.py").read_text(encoding="utf-8")}'
    files[f'{root}/security.py'] = environment.get_template('security.py.jinja').render(header=HEADER, package=package)
    files[f'{root}/app.py'] = environment.get_template('app.py.jinja').render(header=HEADER, package=package)

    by_name = {model.name: model for model in package.models}
    files[f'{root}/models/__init__.py'] = environment.get_template('models_init.py.jinja').render(
        header=HEADER, package=package
    )
    for model in package.models:
        attributes = () if model.is_alias else tuple(_attribute(one) for one in model.fields)
        written = [one.source for one in attributes]
        # `Annotated` and `Field` reach a module through an alias as well as
        # through a constraint, and an alias is written here rather than by the
        # annotator -- so they are found in the source, not predicted.
        body = () if model.is_alias else ('BaseModel',)
        files[f'{root}/models/{model.module}.py'] = environment.get_template('model.py.jinja').render(
            header=HEADER,
            model=model,
            attributes=attributes,
            imports=_imports_for(
                model.annotations,
                by_name,
                Needs(
                    names=(*body, *(name for name in ('Annotated', 'Field') if _mentions(written, name))),
                    runtime=_runtime_of(model.annotations),
                    types_import='..runtime',
                    own=model.name,
                ),
            ),
        )

    files[f'{root}/api/__init__.py'] = environment.get_template('api_init.py.jinja').render(
        header=HEADER, package=package, groups=[(group, class_name(f'{group}-api')) for group in package.groups]
    )
    for group in package.groups:
        routes = [_route(endpoint) for endpoint in package.in_group(group)]
        files[f'{root}/api/{group}.py'] = environment.get_template('group.py.jinja').render(
            header=HEADER,
            group=group,
            interface=class_name(f'{group}-api'),
            routes=routes,
            imports=_group_imports(routes, by_name),
        )

    stubs = [_route(endpoint) for endpoint in package.endpoints]
    files['impl.py'] = environment.get_template('impl.py.jinja').render(
        package=package,
        routes=stubs,
        imports=_stub_imports(package, stubs, by_name),
    )
    files['pyproject.toml'] = environment.get_template('pyproject.toml.jinja').render(package=package)
    files['README.md'] = environment.get_template('README.md.jinja').render(package=package)

    # Everything outside the package is scaffolding rather than an artefact:
    # generated once to make the directory a working project, and edited from
    # then on. `impl.py` is the implementation, `pyproject.toml` grows the
    # dependencies the implementation needs, and the README stops describing a
    # generator and starts describing a service. Regenerating rewrites the
    # package *around* all three.
    return Generated(
        package=package.distribution,
        files=files,
        once=frozenset({'impl.py', 'pyproject.toml', 'README.md'}),
    )


# -- one operation, as source --------------------------------------------------


@dataclass(frozen=True, slots=True)
class Route:
    """One operation: the method to implement, and the route that calls it."""

    endpoint: Endpoint
    #: The abstract method's keyword-only parameters.
    signature: tuple[Parameter, ...]
    #: The route function's parameters, which say where FastAPI reads each from.
    parameters: tuple[Parameter, ...]
    #: `name=name` for every one of them, passed straight through.
    forwarded: tuple[str, ...]
    returns: str
    decorator: str

    @property
    def name(self) -> str:
        return self.endpoint.module


def _route(endpoint: Endpoint) -> Route:
    returns = endpoint.success.annotation.spelling if endpoint.success and endpoint.success.annotation else 'None'
    plain: list[Parameter] = []
    placed: list[Parameter] = []

    for one in endpoint.uri_arguments:
        plain.append(Parameter(one.name, one.annotation.spelling, None, one.docs, one.annotation.plain))
        placed.append(Parameter(one.name, _located(one, 'Path'), None))
    if endpoint.body is not None:
        body = endpoint.body.annotation.spelling
        plain.append(Parameter('body', body, None, f'sent as {endpoint.body.media_type}.'))
        placed.append(Parameter('body', body, None))

    credential = _credential(endpoint)
    if credential is not None:
        plain.append(credential[0])
        placed.append(credential[1])

    for one in endpoint.query_arguments:
        plain.append(_argument(one))
        placed.append(Parameter(one.name, _located(one, 'Query'), _default_of(one)))
    for one in endpoint.header_arguments:
        plain.append(_argument(one))
        placed.append(Parameter(one.name, _located(one, 'Header'), _default_of(one)))

    # Python needs every defaulted parameter last. Nothing else about the order
    # matters to FastAPI, which reads parameters by name.
    ordered = tuple(sorted(placed, key=lambda one: one.required is False))
    return Route(
        endpoint=endpoint,
        signature=tuple(plain),
        parameters=ordered,
        forwarded=tuple(f'{one.name}={one.name}' for one in plain),
        returns=returns,
        decorator=_decorator(endpoint, returns),
    )


def _argument(one: Argument) -> Parameter:
    return Parameter(
        one.name,
        _optionality(one, one.annotation.spelling),
        _default_of(one),
        one.docs,
        _optionality(one, one.annotation.plain),
    )


def _optionality(one: Argument, spelling: str) -> str:
    """`| None` only where the value may genuinely be absent.

    A parameter the document gives a `default:` always has a value by the time a
    handler sees it, so widening it to `None` would make every caller check for
    something that cannot happen.
    """
    return spelling if one.required or one.default is not None else f'{spelling} | None'


def _default_of(one: Argument) -> str | None:
    if one.required:
        return None
    return one.default if one.default is not None else 'None'


def _located(one: Argument, where: str) -> str:
    """One route parameter, with the place FastAPI reads it from.

    The alias is what makes `X-Trace-Id` reachable as `x_trace_id`, and the
    `description` is what puts the author's words in the generated OpenAPI. The
    facets are already in the type, so nothing repeats them here.

    A `Header` is written even with nothing to say, because that is what stops
    it being read from the query string. A `Query` or `Path` with nothing to say
    is left off: FastAPI reads both from the route as it is.
    """
    inner = _optionality(one, one.annotation.spelling)
    arguments = [f'alias={one.wire!r}'] if one.wire != one.name else []
    if one.description:
        arguments.append(f'description={one.description!r}')
    if not arguments and where != 'Header':
        return inner
    return f'Annotated[{inner}, {where}({", ".join(arguments)})]'


def _credential(endpoint: Endpoint) -> tuple[Parameter, Parameter] | None:
    """The credential parameter, as the method takes it and as the route reads it.

    `securedBy: [null, oauth2]` says the call may be made either way, so the
    credential is optional and its absence is not an error. Anything else that
    names a scheme is required, and `requires` answers 401 without it.
    """
    if not endpoint.scheme_names:
        return None
    schemes = ', '.join(f'security.{_constant(name)}' for name in endpoint.scheme_names)
    scopes = f', scopes={_tuple(endpoint.scopes)}' if endpoint.scopes else ''
    if endpoint.optional_auth:
        return (
            Parameter('credential', 'Credential | None', None, 'the credential the caller sent, if any.'),
            Parameter('credential', f'Annotated[Credential | None, Depends(accepts({schemes}{scopes}))]', None),
        )
    return (
        Parameter('credential', 'Credential', None, 'the credential the caller sent.'),
        Parameter('credential', f'Annotated[Credential, Depends(requires({schemes}{scopes}))]', None),
    )


def _decorator(endpoint: Endpoint, returns: str) -> str:
    """The `@api.get(...)` line and its arguments, one per line."""
    arguments = [repr(endpoint.path)]
    if endpoint.success is not None:
        arguments.append(f'status_code={int(endpoint.success.status)}')
    if returns == 'None':
        # FastAPI's default response class writes `null` into the body, which a
        # 204 may not carry at all.
        arguments.append('response_class=Response')
    arguments.append(f'summary={docs.one_line(endpoint.summary)!r}')
    if endpoint.description:
        arguments.append(f'description={docs.one_line(endpoint.description)!r}')
    others = _other_responses(endpoint)
    if others:
        arguments.append(f'responses={others}')
    body = ''.join(f'\n        {argument},' for argument in arguments)
    return f'@api.{endpoint.method}({body}\n    )'


def _other_responses(endpoint: Endpoint) -> str:
    """What `responses=` says, so the generated OpenAPI says what the RAML said.

    Every documented status but the one the method returns -- raising those is
    the implementation's, because the document does not say when. The answered
    status appears too where it carries *headers*, which FastAPI does not know
    about from the return type alone.
    """
    answered = endpoint.success.status if endpoint.success else ''
    entries = []
    for case in endpoint.cases:
        if case.status == answered and not case.headers:
            continue
        parts = [f"'description': {docs.one_line(case.description)!r}"]
        if case.annotation and case.status != answered:
            parts.append(f"'model': {case.annotation.spelling}")
        if case.headers:
            parts.append(f"'headers': {_documented_headers(case)}")
        entries.append(f'{int(case.status)}: {{{", ".join(parts)}}}')
    return '{' + ', '.join(entries) + '}' if entries else ''


#: A header's type, as OpenAPI spells it. Everything crosses the wire as text,
#: so an unknown type is a string rather than a guess; the ones below are the
#: document being specific about what that text holds.
_HEADER_SCHEMA = {
    'str': "{'type': 'string'}",
    'int': "{'type': 'integer'}",
    'float': "{'type': 'number'}",
    'bool': "{'type': 'boolean'}",
    'datetime.datetime': "{'type': 'string', 'format': 'date-time'}",
    'datetime.date': "{'type': 'string', 'format': 'date'}",
    'datetime.time': "{'type': 'string', 'format': 'time'}",
}


def _documented_headers(case: Case) -> str:
    """The headers a response carries, as OpenAPI describes one.

    Publishing them is not producing them: a handler that has to *set* a header
    needs somewhere to set it, which is a question about signatures rather than
    about documents.
    """
    entries = []
    for one in case.headers:
        parts = [
            f"'required': {one.required}",
            f"'schema': {_HEADER_SCHEMA.get(one.annotation.plain, _HEADER_SCHEMA['str'])}",
        ]
        if one.description:
            parts.insert(0, f"'description': {one.description!r}")
        entries.append(f'{one.wire!r}: {{{", ".join(parts)}}}')
    return '{' + ', '.join(entries) + '}'


def _attribute(one: Field) -> Parameter:
    """One model attribute.

    A wire name that is not a Python name becomes an alias, and the alias goes
    *outside* any constraint the type carries: a `FieldInfo` nested inside a
    union member is not the field's, and pydantic would never see it.

    The alias is the only name accepted. `populate_by_name` would let the
    attribute's own name through as well, which is a request the document does
    not describe -- the cost of that is having to write `Book(createdAt=...)`
    rather than `Book(created_at=...)`, and the server is the party that decides
    what the document means.
    """
    optional = not one.required and one.default is None
    inner = f'{one.annotation.spelling} | None' if optional else one.annotation.spelling
    bare = f'{one.annotation.plain} | None' if optional else one.annotation.plain
    if one.wire != one.name:
        inner = f'Annotated[{inner}, Field(alias={one.wire!r})]'
    default = None if one.required else (one.default if one.default is not None else 'None')
    return Parameter(one.name, inner, default, one.docs, bare)


# -- assembling ----------------------------------------------------------------


def _constant(name: str) -> str:
    from ....naming import module_name  # noqa: PLC0415 - one call, and the module is already loaded

    return module_name(name).upper()


def _tuple(values: tuple[str, ...]) -> str:
    inner = ', '.join(repr(value) for value in values)
    return f'({inner},)' if len(values) == 1 else f'({inner})'


def _runtime_of(annotations: Iterable[Annotation]) -> tuple[str, ...]:
    return tuple(sorted({name for one in annotations for name in one.runtime}))


def _environment() -> jinja2.Environment:
    environment = jinja2.Environment(
        loader=jinja2.FileSystemLoader(_TEMPLATES),
        autoescape=False,  # noqa: S701 - the output is Python, not HTML
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    environment.filters['repr'] = repr
    environment.filters['one_line'] = docs.one_line
    environment.filters['summary'] = docs.summary
    environment.filters['details'] = docs.details
    environment.filters['attribute'] = _documented
    return environment


def _documented(one: Parameter, indent: int = 8) -> str:
    """One `Attributes:` or `Args:` line, wrapped."""
    head = f'{" " * indent}{one.name} ({one.documented})'
    if not one.docs:
        return head
    return docs.wrapped(f'{head}: {docs.one_line(one.docs)}', indent + 4)


#: Where every name a generated module imports comes from.
_FROM: Final = {
    'abc': Source(None, third_party=False),
    'datetime': Source(None, third_party=False),
    'Annotated': Source('typing', third_party=False),
    'Any': Source('typing', third_party=False),
    'Literal': Source('typing', third_party=False),
    'override': Source('typing', third_party=False),
    'APIRouter': Source('fastapi', third_party=True),
    'Depends': Source('fastapi', third_party=True),
    'FastAPI': Source('fastapi', third_party=True),
    'Header': Source('fastapi', third_party=True),
    'Path': Source('fastapi', third_party=True),
    'Query': Source('fastapi', third_party=True),
    'Response': Source('fastapi', third_party=True),
    'UploadFile': Source('fastapi', third_party=True),
    'AfterValidator': Source('pydantic', third_party=True),
    'BaseModel': Source('pydantic', third_party=True),
    'Field': Source('pydantic', third_party=True),
}


def _imports_for(annotations: Iterable[Annotation], by_name: Mapping[str, Model], needs: Needs) -> Imports:
    return imports_for(annotations, by_name, needs, _FROM)


#: Names this module writes into a signature, which no annotation knows about.
#: They are found in the source rather than predicted from the plan, because
#: predicting them drifted the moment `_located` started leaving a `Query()`
#: with nothing to say off -- the parameter lost the call and kept the import,
#: and an unused import is an error in the generated package's own gate.
_WRITTEN = ('Annotated', 'Depends', 'Header', 'Path', 'Query')


#: Anything that is not part of a Python name, so that a name can be looked for
#: whole: `Path` must not be found inside `PathLike`.
_NOT_A_NAME: Final = re.compile(r'[^0-9A-Za-z_]+')


def _mentions(sources: Iterable[str], name: str) -> bool:
    return any(name in _NOT_A_NAME.sub(' ', text).split() for text in sources)


def _group_imports(routes: list[Route], by_name: Mapping[str, Model]) -> Imports:
    """What one `api/<group>.py` imports.

    Only the *structural* source is read -- the parameters and the return types.
    A `description=` carries whatever the author wrote, and a sentence beginning
    "Response" is not a use of `fastapi.Response`.
    """
    written = [one.source for route in routes for one in route.parameters]
    annotations = tuple(one for route in routes for one in route.endpoint.annotations)
    names = ['abc', 'APIRouter', *(name for name in _WRITTEN if _mentions(written, name))]
    if any(route.returns == 'None' for route in routes):
        # FastAPI's default response class writes `null`, which a 204 may not
        # carry, so those routes name `Response` in their decorator.
        names.append('Response')

    lines = []
    secured = [route for route in routes if route.endpoint.scheme_names]
    if secured:
        lines.append('from .. import security')
        wanted = sorted({'accepts' if route.endpoint.optional_auth else 'requires' for route in secured})
        lines.append(f'from ..runtime import {", ".join(["Credential", *wanted])}')
    return _imports_for(
        annotations,
        by_name,
        Needs(names=tuple(names), lines=tuple(lines), types_import='..runtime', model_prefix='..models.'),
    )


def _stub_imports(package: Package, routes: list[Route], by_name: Mapping[str, Model]) -> Imports:
    """What `impl.py` imports.

    It sits beside the package rather than inside it, so every import is
    absolute, and the models come from `models` in one line rather than one
    module each -- it is a file somebody is about to edit.
    """
    written = [one.source for route in routes for one in route.signature]
    annotations = tuple(one for route in routes for one in route.endpoint.annotations)
    # `override` on every method, always. It is what turns an operation the
    # document dropped into a type error: the method is left with nothing to
    # override, where otherwise it would sit here routing nowhere and checking
    # out fine.
    names = ('override', *(name for name in ('Annotated', 'Field') if _mentions(written, name)))
    lines = [f'from {package.module} import Api, create_app']
    if _mentions(written, 'Credential'):
        lines.append(f'from {package.module}.runtime import Credential')

    reached = _imports_for(annotations, by_name, Needs(names=names, lines=tuple(lines))).models
    if reached:
        named = ', '.join(model.name for model in reached)
        lines.append(f'from {package.module}.models import {named}')
    # `by_name` empty, so no per-module import is added beside the one above.
    return _imports_for(annotations, {}, Needs(names=names, lines=tuple(lines)))
