# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""Bookstore API v2.

A worked example exercising every construct the tree carries — including **Markdown** in a description, which is what the RAML spec says every `description:` is.

See [Getting started](#) for the `{tenant}` you will need.
"""

from __future__ import annotations

from .client import AuthenticatedClient, Client

__all__ = ['AuthenticatedClient', 'Client']

BASE_URL = 'https://{tenant}.books.example.com/{version}'
"""The `baseUri:` the document declares.

A templated base URI still carries its `{...}` tokens. Supply what they stand
for yourself; the document does not say.
"""
