"""Turn a plan and a set of templates into files.

Two parts of the output are not templated, for different reasons.

**The runtime is copied.** `client.py`, `types.py` and `errors.py` are ordinary
Python under `runtime/`, and they arrive in the generated package byte for byte.
The test suite runs them and a reader can read them. A template that produced
them instead would be a file nothing could check.

**The import block is computed.** An earlier version ran
`ruff check --fix --select I,F401` over the finished files. That made the output
depend on the installed ruff version, so upgrading ruff changed the golden
record for reasons unrelated to this package. It also failed silently where ruff
was missing: `check --fix-only` and "no such module" both exit 1, so imports
came out unsorted and unused ones stayed. A module's imports follow from its own
plan, so this module works them out and runs no subprocess.
"""

from __future__ import annotations

import pathlib
import re
import textwrap
from dataclasses import dataclass, replace
from typing import TYPE_CHECKING, Final, Literal

import jinja2

from ...targets import Generated, Settings
from .annotate import fill
from .plan import plan

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from ...reader import Tree
    from .annotate import Annotation
    from .plan import Endpoint, Field, Model

__all__ = ['generate_python']

_HERE = pathlib.Path(__file__).resolve().parent
_TEMPLATES = _HERE / 'templates'
_RUNTIME = _HERE / 'runtime'

HEADER = '# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.'


@dataclass(frozen=True, slots=True)
class _Source:
    """Where one importable name lives."""

    #: `None` when the name is itself a module, as `datetime` and `httpx` are.
    module: str | None
    third_party: bool


@dataclass(frozen=True, slots=True)
class Needs:
    """What one generated module's own body imports.

    Separate from what its *types* import, which the annotations already know.
    """

    #: Names to resolve through `_FROM`, such as `Mapping` or `HTTPStatus`.
    names: tuple[str, ...] = ()
    #: Relative imports, written out: they vary with the module's position.
    lines: tuple[str, ...] = ()
    #: Names from the generated package's own `types` module.
    runtime: tuple[str, ...] = ()
    #: How this module reaches `types` and the models beside it.
    types_import: str = '..types'
    model_prefix: str = '.'
    #: The model this module defines, which it must not import.
    own: str | None = None


@dataclass(frozen=True, slots=True)
class Imports:
    """The whole import section of one generated module, already ordered.

    Ordered the way isort would, in four blocks separated by a blank line:
    `__future__`, the standard library, third-party, then this package's own.
    A plain `import x` comes before a `from x import y` within a block, and the
    names in one `from` run constants, then classes, then functions.
    """

    block: str
    models: tuple[Model, ...]


def generate_python(tree: Tree, settings: Settings) -> Generated:
    """The whole package, as paths to text."""
    package = plan(tree, settings)
    environment = _environment()
    files: dict[str, str] = {}
    root = package.module

    files[f'{root}/__init__.py'] = environment.get_template('package_init.py.jinja').render(
        header=HEADER, package=package
    )
    files[f'{root}/py.typed'] = ''
    for name in ('types.py', 'errors.py', 'client.py'):
        files[f'{root}/{name}'] = f'{HEADER}\n{(_RUNTIME / name).read_text(encoding="utf-8")}'

    by_name = {model.name: model for model in package.models}
    files[f'{root}/models/__init__.py'] = environment.get_template('models_init.py.jinja').render(
        header=HEADER, package=package
    )
    for model in package.models:
        # An alias is a bare assignment. It still *names* the models it is built
        # from, so those are imported; it defines no class and converts nothing,
        # so what a dataclass body and a converter would need never applies.
        annotations = (
            [replace(one, runtime=frozenset()) for one in model.annotations] if model.is_alias else model.annotations
        )
        files[f'{root}/models/{model.module}.py'] = environment.get_template('model.py.jinja').render(
            header=HEADER,
            model=model,
            imports=_imports_for(
                annotations,
                by_name,
                Needs(
                    names=() if model.is_alias else ('Mapping', 'dataclass', 'Any'),
                    runtime=_model_runtime(model),
                    own=model.name,
                ),
            ),
        )

    files[f'{root}/api/__init__.py'] = environment.get_template('api_init.py.jinja').render(
        header=HEADER, package=package
    )
    for group in package.groups:
        endpoints = package.in_group(group)
        files[f'{root}/api/{group}/__init__.py'] = environment.get_template('group_init.py.jinja').render(
            header=HEADER, group=group, endpoints=endpoints
        )
        for endpoint in endpoints:
            optional = any(not one.required for one in endpoint.arguments)
            clients = 'AuthenticatedClient, Client' if endpoint.optional_auth else _client_type(endpoint)
            files[f'{root}/api/{group}/{endpoint.module}.py'] = environment.get_template('endpoint.py.jinja').render(
                header=HEADER,
                endpoint=endpoint,
                client_type=_client_type(endpoint),
                imports=_imports_for(
                    endpoint.annotations,
                    by_name,
                    Needs(
                        names=('HTTPStatus', 'Any', 'httpx'),
                        lines=('from ... import errors', f'from ...client import {clients}'),
                        # `UNSET` and `Unset` only where an argument is optional.
                        runtime=('UNSET', 'Mismatch', 'Response', 'Unset', 'reading')
                        if optional
                        else ('Mismatch', 'Response', 'reading'),
                        types_import='...types',
                        model_prefix='...models.',
                    ),
                ),
            )

    files[f'{root}/security.py'] = environment.get_template('security.py.jinja').render(header=HEADER, package=package)
    files['pyproject.toml'] = environment.get_template('pyproject.toml.jinja').render(package=package)
    files['README.md'] = environment.get_template('README.md.jinja').render(package=package)

    return Generated(package=package.distribution, files=files)


# -- assembling ----------------------------------------------------------------


def _model_runtime(model: Model) -> tuple[str, ...]:
    if not model.fields:
        return ()
    if any(one.required for one in model.fields):
        return ('UNSET', 'Unset', 'absent')
    return ('UNSET', 'Unset')


def _client_type(endpoint: Endpoint) -> str:
    """Which client a call needs, from what the document secured it with."""
    if endpoint.requires_auth:
        return 'AuthenticatedClient'
    return 'AuthenticatedClient | Client' if endpoint.optional_auth else 'Client'


def _environment() -> jinja2.Environment:
    environment = jinja2.Environment(
        loader=jinja2.FileSystemLoader(_TEMPLATES),
        autoescape=False,  # noqa: S701 - the output is Python, not HTML
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    environment.filters['repr'] = repr
    environment.filters['one_line'] = _one_line
    environment.filters['summary'] = _summary
    environment.filters['details'] = _details
    environment.filters['format_with'] = _format_with
    environment.filters['attribute'] = _attribute
    return environment


def _one_line(text: str | None) -> str:
    r"""A description, as one line.

    For somewhere that has room for one: an `Attributes:` entry, a `#:` comment.
    A whole description goes through `_details`, which keeps its shape.

    RAML says every `description:` is Markdown, so it may contain anything --
    including `\"\"\"`, which would end the docstring it is being written into.
    Generated docstrings are raw, so a `pattern:` like `^\\d{13}$` reads as the
    author wrote it rather than as `^\\\\d{13}$`; a raw string cannot escape a
    quote, so the one sequence that could close one early is replaced rather
    than escaped.
    """
    return ' '.join((text or '').replace('"""', "'''").split())


#: A Markdown list item. An author writes lists in a `description:`, and the
#: shape of one has to survive being put into a docstring.
_BULLET: Final = re.compile(r'^([*+-]|\d+[.)])\s+')


@dataclass(frozen=True, slots=True)
class _Block:
    """One paragraph or one list item of a description."""

    kind: Literal['paragraph', 'item']
    text: str


def _blocks(text: str | None) -> list[_Block]:
    """A description, as the paragraphs and list items the author wrote.

    Collapsing the whole thing to one line is what put `* price is the current
    price` in the middle of a sentence. A blank line ends a paragraph, a bullet
    starts an item, and an indented line under an item continues it.
    """
    found: list[_Block] = []
    current: list[str] = []
    kind: Literal['paragraph', 'item'] = 'paragraph'

    def flush() -> None:
        if current:
            found.append(_Block(kind, _one_line(' '.join(current))))
            current.clear()

    for raw in (text or '').replace('\r\n', '\n').split('\n'):
        line = raw.strip()
        if not line:
            flush()
            kind = 'paragraph'
        elif _BULLET.match(line):
            flush()
            kind = 'item'
            current.append(line)
        elif kind == 'item' and raw[:1].isspace():
            current.append(line)
        else:
            if kind == 'item':
                flush()
                kind = 'paragraph'
            current.append(line)
    flush()
    return found


def _summary(text: str | None) -> str:
    """The first sentence, for the line a docstring opens on."""
    found = _blocks(text)
    if not found:
        return ''
    head, stop, _ = found[0].text.partition('. ')
    return f'{head}.' if stop else found[0].text


def _details(text: str | None, indent: int = 4) -> str:
    """Everything after the first sentence, with its shape kept.

    Paragraphs are reflowed and separated by a blank line. A list item keeps its
    bullet, sits on a line of its own, and hangs its continuation under itself.
    """
    found = _blocks(text)
    if not found:
        return ''
    _, stop, rest = found[0].text.partition('. ')
    remaining = [_Block('paragraph', rest)] if stop and rest.strip() else []
    remaining += found[1:]
    if not remaining:
        return ''

    written: list[str] = []
    for index, block in enumerate(remaining):
        # Consecutive items are one list, so nothing goes between them.
        if index and not (block.kind == 'item' and remaining[index - 1].kind == 'item'):
            written.append('')
        written.append(_wrapped(block.text, indent + 2 if block.kind == 'item' else indent, first=indent))
    return '\n'.join(written)


def _wrapped(text: str, indent: int, first: int = 0) -> str:
    """Wrapped, but never inside a word.

    `break_long_words` off, because the words here include a `pattern:` -- and
    `^(?:[A-Z]{2}-` on one line with `)?(?:AISLE` on the next reads as part of
    the pattern. A line that runs long is honest; a regex cut in half is not.
    """
    return textwrap.fill(
        text,
        width=100,
        initial_indent=' ' * first,
        subsequent_indent=' ' * indent,
        break_long_words=False,
        break_on_hyphens=False,
    )


def _attribute(one: Field, indent: int = 8) -> str:
    """One `Attributes:` line, wrapped.

    A description and its constraints run to a few hundred characters on a type
    whose author had something to say, and generated code is still code.
    """
    head = f'{" " * indent}{one.name} ({one.annotation.spelling})'
    if not one.docs:
        return head
    return _wrapped(f'{head}: {_one_line(one.docs)}', indent + 4)


def _format_with(template: str, value: str) -> str:
    """`{}` in an annotation's encode/decode form, filled in."""
    return fill(template, value)


#: Where every name a generated module imports comes from. `module` is `None`
#: for a name that is imported as a module in its own right, and `third_party`
#: decides which block the import lands in.
_FROM: Final = {
    'datetime': _Source(None, third_party=False),
    'httpx': _Source(None, third_party=True),
    'Any': _Source('typing', third_party=False),
    'Literal': _Source('typing', third_party=False),
    'Mapping': _Source('collections.abc', third_party=False),
    'dataclass': _Source('dataclasses', third_party=False),
    'HTTPStatus': _Source('http', third_party=False),
}


def _imports_for(annotations: Iterable[Annotation], by_name: Mapping[str, Model], needs: Needs) -> Imports:
    """Everything one module imports.

    Two sources, and neither can see the other. The annotations say what the
    *types* need — `datetime` for a date, `Literal` for an enum, a model class,
    `File`. `needs` says what the module's own body needs, which no annotation
    knows: a dataclass needs `dataclass` and `Mapping`, an endpoint needs
    `httpx` and `HTTPStatus`.
    """
    listed = tuple(annotations)
    wanted = {name for one in listed for name in one.models}
    # A recursive type names itself, and a module cannot import itself. The
    # self-reference is legal because every generated module opens with
    # `from __future__ import annotations`, and finite because of the marker.
    wanted.discard(needs.own or '')
    models = tuple(by_name[name] for name in sorted(wanted) if name in by_name)

    standard: list[str] = []
    third_party: list[str] = []
    by_module: dict[str, list[str]] = {}
    for name in {*needs.names, *(name for one in listed for name in one.imports)}:
        source = _FROM[name]
        if source.module is None:
            (third_party if source.third_party else standard).append(f'import {name}')
        else:
            by_module.setdefault(source.module, []).append(name)
    standard += [
        f'from {module} import {", ".join(sorted(names, key=_by_kind))}' for module, names in by_module.items()
    ]

    own = list(needs.lines)
    from_runtime = sorted({*needs.runtime, *(name for one in listed for name in one.runtime)}, key=_by_kind)
    if from_runtime:
        own.append(f'from {needs.types_import} import {", ".join(from_runtime)}')
    own += [f'from {needs.model_prefix}{model.module} import {model.name}' for model in models]

    blocks = [
        ['from __future__ import annotations'],
        sorted(standard, key=_import_order),
        sorted(third_party, key=_import_order),
        sorted(own, key=_import_order),
    ]
    return Imports(block='\n\n'.join('\n'.join(block) for block in blocks if block), models=models)


def _by_kind(name: str) -> tuple[int, str]:
    """Constants, then classes, then functions — isort's `order-by-type`."""
    if name.isupper():
        return (0, name)
    return (1, name) if name[:1].isupper() else (2, name)


def _import_order(line: str) -> tuple[int, str]:
    """`import x` before `from x import y`, then by module, most dots first."""
    if line.startswith('import '):
        return (0, line.removeprefix('import '))
    return (1, line.split(' ', 2)[1])
