"""Turn a plan and a set of templates into a client package.

**The runtime is copied.** `client.py`, `types.py` and `errors.py` are ordinary
Python under `runtime/`, and they arrive in the generated package byte for byte.
The test suite runs them and a reader can read them. A template that produced
them instead would be a file nothing could check.

The import block is computed rather than formatted; `targets/shared/imports.py`
says why.
"""

from __future__ import annotations

import pathlib
from dataclasses import replace
from typing import TYPE_CHECKING, Final

import jinja2

from ...targets import Generated, Settings
from ..shared import docs
from ..shared.annotate import fill
from ..shared.imports import Needs, Source, imports_for
from ..shared.plan import plan
from .annotate import make_annotator

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    from ...reader import Tree
    from ..shared.annotate import Annotation
    from ..shared.imports import Imports
    from ..shared.plan import Endpoint, Model

__all__ = ['generate_python']

_HERE = pathlib.Path(__file__).resolve().parent
_TEMPLATES = _HERE / 'templates'
_RUNTIME = _HERE / 'runtime'

HEADER = '# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.'

#: The modules the generated package root already uses, so no declared type may
#: be given one of their names.
_RESERVED = frozenset({'types', 'client', 'errors'})


def generate_python(tree: Tree, settings: Settings) -> Generated:
    """The whole package, as paths to text."""
    package = plan(tree, settings, make_annotator, _RESERVED)
    environment = _environment()
    files: dict[str, str] = {}
    root = package.module

    files[f'{root}/__init__.py'] = environment.get_template('package_init.py.jinja').render(
        header=HEADER, package=package
    )
    files[f'{root}/py.typed'] = ''
    for name in ('types.py', 'errors.py', 'client.py'):
        files[f'{root}/{name}'] = f'{HEADER}\n{(_RUNTIME / name).read_text(encoding="utf-8")}'

    by_name = {model.name: model for model in package.models}
    files[f'{root}/models/__init__.py'] = environment.get_template('models_init.py.jinja').render(
        header=HEADER, package=package
    )
    for model in package.models:
        # An alias is a bare assignment. It still *names* the models it is built
        # from, so those are imported; it defines no class and converts nothing,
        # so what a dataclass body and a converter would need never applies.
        annotations = (
            [replace(one, runtime=frozenset()) for one in model.annotations] if model.is_alias else model.annotations
        )
        files[f'{root}/models/{model.module}.py'] = environment.get_template('model.py.jinja').render(
            header=HEADER,
            model=model,
            imports=_imports_for(
                annotations,
                by_name,
                Needs(
                    names=() if model.is_alias else ('Mapping', 'dataclass', 'Any'),
                    runtime=_model_runtime(model),
                    own=model.name,
                ),
            ),
        )

    files[f'{root}/api/__init__.py'] = environment.get_template('api_init.py.jinja').render(
        header=HEADER, package=package
    )
    for group in package.groups:
        endpoints = package.in_group(group)
        files[f'{root}/api/{group}/__init__.py'] = environment.get_template('group_init.py.jinja').render(
            header=HEADER, group=group, endpoints=endpoints
        )
        for endpoint in endpoints:
            optional = any(not one.required for one in endpoint.arguments)
            clients = 'AuthenticatedClient, Client' if endpoint.optional_auth else _client_type(endpoint)
            files[f'{root}/api/{group}/{endpoint.module}.py'] = environment.get_template('endpoint.py.jinja').render(
                header=HEADER,
                endpoint=endpoint,
                client_type=_client_type(endpoint),
                imports=_imports_for(
                    endpoint.annotations,
                    by_name,
                    Needs(
                        names=('HTTPStatus', 'Any', 'httpx'),
                        lines=('from ... import errors', f'from ...client import {clients}'),
                        # `UNSET` and `Unset` only where an argument is optional.
                        runtime=('UNSET', 'Mismatch', 'Response', 'Unset', 'reading')
                        if optional
                        else ('Mismatch', 'Response', 'reading'),
                        types_import='...types',
                        model_prefix='...models.',
                    ),
                ),
            )

    files[f'{root}/security.py'] = environment.get_template('security.py.jinja').render(header=HEADER, package=package)
    files['pyproject.toml'] = environment.get_template('pyproject.toml.jinja').render(package=package)
    files['README.md'] = environment.get_template('README.md.jinja').render(package=package)

    return Generated(package=package.distribution, files=files)


# -- assembling ----------------------------------------------------------------


def _model_runtime(model: Model) -> tuple[str, ...]:
    if not model.fields:
        return ()
    if any(one.required for one in model.fields):
        return ('UNSET', 'Unset', 'absent')
    return ('UNSET', 'Unset')


def _client_type(endpoint: Endpoint) -> str:
    """Which client a call needs, from what the document secured it with."""
    if endpoint.requires_auth:
        return 'AuthenticatedClient'
    return 'AuthenticatedClient | Client' if endpoint.optional_auth else 'Client'


def _environment() -> jinja2.Environment:
    environment = jinja2.Environment(
        loader=jinja2.FileSystemLoader(_TEMPLATES),
        autoescape=False,  # noqa: S701 - the output is Python, not HTML
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    environment.filters['repr'] = repr
    environment.filters['one_line'] = docs.one_line
    environment.filters['summary'] = docs.summary
    environment.filters['details'] = docs.details
    environment.filters['format_with'] = fill
    environment.filters['attribute'] = docs.attribute
    return environment


#: Where every name a generated module imports comes from. `module` is `None`
#: for a name that is imported as a module in its own right, and `third_party`
#: decides which block the import lands in.
_FROM: Final = {
    'datetime': Source(None, third_party=False),
    'httpx': Source(None, third_party=True),
    'Any': Source('typing', third_party=False),
    'Literal': Source('typing', third_party=False),
    'Mapping': Source('collections.abc', third_party=False),
    'dataclass': Source('dataclasses', third_party=False),
    'HTTPStatus': Source('http', third_party=False),
}


def _imports_for(annotations: Iterable[Annotation], by_name: Mapping[str, Model], needs: Needs) -> Imports:
    return imports_for(annotations, by_name, needs, _FROM)
