/**
 * The `pyraml tree` contract.
 *
 * GENERATED by `python -m pyraml.views.bindings` -- do not edit. The key sets
 * are read from `pyraml/views/tree.py` and the facets from the kind classes in
 * `pyraml/types/`, so a facet added to a kind arrives here without this file
 * being touched. `tests/unit/test_bindings.py` fails when the two disagree.
 *
 * The metamodel is three constructs (docs/16-graph.md section 11.10):
 *
 *   {"$ref": <address>}                            a link -- look the target up
 *   {"type": "recursive", "head": {"$ref": ...}}   repeats here, do not expand
 *   anything else                                  containment -- descend
 *
 * A consumer descends containment, follows a link when it chooses to, and stops
 * at a recursion marker. It maintains no ancestor set. Requires
 * `ParseOptions(unwrap=True)`, which `pyraml tree` uses.
 */

/** A structural address: stable across re-parses, and the identity of a node. */
export type Address = string;

export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

/** A link. Its sole key is the test -- an expanded shape carries `id` as well. */
export interface Ref {
  $ref: Address;
}

/**
 * A type, of any of the seventeen kinds.
 *
 * Flat rather than a union over `type` because that is how it arrives: the
 * base fields and the concrete kind's facets are merged onto one object.
 *
 * A `Fraction`-valued facet -- `minimum` and `maximum` on a number,
 * `multipleOf` anywhere -- arrives as an exact ratio in a string, so
 * `multipleOf: 0.01` reads `"1/100"`. The parser never passes a number
 * through `float`, on either side of a comparison, and neither should a
 * consumer that means to agree with it.
 */
export interface Shape {
  id: Address | null;
  name: string | null;
  type: string;
  inherits?: (Shape | Ref)[];
  custom_facets?: Record<string, Json>;
  declares_facets?: string[];
  annotations?: Applied[];
  type_expr?: string;
  display_name?: string;
  description?: string;
  required?: boolean;
  default?: Json;
  example?: Json;
  examples?: Record<string, Json>;
  enum?: Json[];
  xml?: Json;
  allowed_targets?: string[];

  /* Facets, by the kind that declares each. */
  additional_properties?: boolean; // Object
  any_of?: (Shape | Ref)[]; // Union
  discriminator?: string; // Object
  discriminator_value?: Json; // Object
  file_types?: string[]; // File
  format?: string; // Number, Integer, DateTime
  items?: Shape | Ref; // Array
  max_items?: number; // Array
  max_length?: number; // String, File
  max_properties?: number; // Object
  maximum?: string | number; // Number, Integer -- a ratio, e.g. "1/100" for 0.01
  min_items?: number; // Array
  min_length?: number; // String, File
  min_properties?: number; // Object
  minimum?: string | number; // Number, Integer -- a ratio, e.g. "1/100" for 0.01
  multiple_of?: string; // Number, Integer -- a ratio, e.g. "1/100" for 0.01
  pattern?: string; // String
  pattern_properties?: Record<string, PatternProperty>; // Object
  properties?: Record<string, Property>; // Object
  unique_items?: boolean; // Array
}

export interface Document {
  base: string;
  entry_point: EntryPoint | null;
  types: Record<string, Record<string, Shape>>;
  annotation_types: Record<string, Record<string, Shape>>;
  security_schemes: Record<string, Record<string, SecurityScheme>>;
  endpoints: Record<string, Endpoint>;
  annotations: DocumentAnnotation[];
}

export interface EntryPoint {
  kind: string;
  base_uri_parameters?: Record<string, Parameter>;
  documentation?: { title: string; content: string }[];
  annotations?: Applied[];
  title?: string;
  version?: string;
  base_uri?: string;
  media_types?: string[];
  protocols?: string[];
  usage?: string;
  description?: string;
}

export interface SecurityScheme {
  id: Address | null;
  name: string;
  type: string;
  described_by?: DescribedBy;
  annotations?: Applied[];
  display_name?: string;
  description?: string;
  settings?: Record<string, Json>;
}

export interface DescribedBy {
  query_string?: Shape | Ref | null;
  responses?: Record<string, Response>;
  headers?: Record<string, Parameter>;
  query_parameters?: Record<string, Parameter>;
}

export interface Endpoint {
  id: Address | null;
  operations: Record<string, Operation>;
  secured_by: SecuredBy[];
  uri_parameters?: Record<string, Parameter>;
  annotations?: Applied[];
  display_name?: string;
  description?: string;
}

export interface Operation {
  id: Address | null;
  responses: Record<string, Response>;
  description?: string;
  display_name?: string;
  secured_by?: SecuredBy[];
  annotations?: Applied[];
  query_string?: Shape | Ref | null;
  bodies?: Record<string, Shape | Ref | null>;
  headers?: Record<string, Parameter>;
  query_parameters?: Record<string, Parameter>;
}

export interface Response {
  description?: string;
  headers?: Record<string, Parameter>;
  bodies?: Record<string, Shape | Ref | null>;
  annotations?: Applied[];
}

export interface SecuredBy {
  name: string;
  is_null: boolean;
  bound: boolean;
  declaration: Address | null;
  scopes: string[] | null;
}

export interface Applied {
  name: string;
  type: Address | null;
  value: Json;
}

export interface DocumentAnnotation {
  name: string;
  target: string;
  type: Address | null;
  value: Json;
}

export interface Recursion {
  type: 'recursive';
  name: string | null;
  head: Ref;
}

export interface Property {
  required: boolean;
  type: Shape | Ref | null;
}

export interface PatternProperty {
  pattern: string;
  type: Shape | Ref | null;
}

export interface Parameter {
  binding: string;
  required: boolean;
  type: Shape | Ref | null;
}
