# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""The operations the document describes, grouped by the first path segment.

Each module holds four entry points. `sync_detailed` and `asyncio_detailed`
return a `Response[T]` carrying the status, the raw content and the parsed body;
`sync` and `asyncio` return the parsed body alone.

* `books` — /books, /books/{isbn}
* `shelves` — /shelves
* `deliveries` — /deliveries
* `publications` — /publications
* `search` — /search
"""
