# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""The `securitySchemes:` this API declares, as credential mechanics.

Each `SchemeSpec` says which header carries the credential and what precedes it,
so a scheme that names its own header through `describedBy:` gets the header the
API is actually reading:

    from bookstore_api import security

    client = security.OAUTH2.client(
        base_url=...,
        token=...,
    )

Every module under `api/` carries a `SCHEMES` tuple naming which of these its
operation accepts.
"""

from __future__ import annotations

from .client import SchemeSpec

OAUTH2 = SchemeSpec(
    name='oauth2',
    type='OAuth 2.0',
    header_name='Authorization',
    prefix='Bearer',
    scopes=(
        'read:books',
        'write:books',
        'delete:books',
        'read:reviews',
        'write:reviews',
        'admin:catalogue',
    ),
)
"""Standard three-legged flow."""

MACHINE_TOKEN = SchemeSpec(
    name='machineToken',
    type='OAuth 2.0',
    header_name='Authorization',
    prefix='Bearer',
    scopes=(
        'read:books',
        'read:deliveries',
    ),
)
"""Two-legged client credentials, for server-to-server callers that have no user to send through a browser."""

BASIC = SchemeSpec(
    name='basic',
    type='Basic Authentication',
    header_name='Authorization',
    prefix='Basic',
)
"""Username and password, for server-to-server callers only."""

SCHEMES: dict[str, SchemeSpec] = {
    'oauth2': OAUTH2,
    'machineToken': MACHINE_TOKEN,
    'basic': BASIC,
}
"""Every scheme, by the name the document gave it."""

__all__ = [
    'BASIC',
    'MACHINE_TOKEN',
    'OAUTH2',
    'SCHEMES',
]
