# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""books — 4 operations.

* `post_books` — `POST /books`
* `get_books` — `GET /books`
* `get_books_isbn` — `GET /books/{isbn}`
* `delete_books_isbn` — `DELETE /books/{isbn}`
"""
