# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.book import Book
from ...types import Mismatch, Response, reading

PATH = '/books/{isbn}'
"""The path this module calls, before its `{...}` tokens are filled in."""

METHOD = 'get'
"""The HTTP method this module uses."""

SCHEMES = ('oauth2',)
"""The `securedBy:` schemes this operation accepts.

`security.py` holds the mechanics of each: which header carries the credential,
and what precedes it.
"""


def _kwargs(
    *,
    isbn: str,
) -> dict[str, Any]:
    path = PATH
    path = path.replace('{isbn}', str(isbn))

    params: dict[str, Any] = {}

    headers: dict[str, str] = {}

    out: dict[str, Any] = {'method': METHOD, 'url': path}
    if params:
        out['params'] = params
    if headers:
        out['headers'] = headers
    return out


def _parse(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Book | None:
    if response.status_code == 200:
        payload = response.json()
        return Book.from_dict(payload)
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    return None


def _build(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Book]:
    """The response, and whatever could be made of its body.

    Nothing a *payload* does gets out of here. A body that is not what the
    document describes -- a missing property, an unreadable date, HTML where
    JSON was promised -- lands in `mismatches`, and `content` still holds the
    bytes. Only `errors.UnexpectedStatus`, which the caller asked for, and a
    transport error, which is not about the payload, travel further.
    """
    parsed: Book | None = None
    with reading(strict=client.strict) as mismatches:
        try:
            parsed = _parse(client=client, response=response)
        except errors.ClientError:
            raise
        except Exception as unreadable:  # noqa: BLE001 - a payload may be anything at all
            mismatches.append(Mismatch('Book', '', f'{type(unreadable).__name__}: {unreadable}'))
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=parsed,
        mismatches=tuple(mismatches),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    isbn: str,
) -> Response[Book]:
    r"""Retrieve a book

    Returns one book by its ISBN-13.

    Args:
        isbn (str): (pattern: ^\d{13}$)

    Responses:
        200

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[Book] -- the status, the raw content and the parsed body.
    """

    response = client.get_httpx_client().request(**_kwargs(
        isbn=isbn,
    ))
    return _build(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    isbn: str,
) -> Book | None:
    r"""Retrieve a book

    Returns one book by its ISBN-13.

    Args:
        isbn (str): (pattern: ^\d{13}$)

    Responses:
        200

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Book -- the parsed body of the 200 response, or None.
    """

    return sync_detailed(
        client=client,
        isbn=isbn,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    isbn: str,
) -> Response[Book]:
    r"""Retrieve a book

    Returns one book by its ISBN-13.

    Args:
        isbn (str): (pattern: ^\d{13}$)

    Responses:
        200

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[Book] -- the status, the raw content and the parsed body.
    """

    response = await client.get_async_httpx_client().request(**_kwargs(
        isbn=isbn,
    ))
    return _build(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    isbn: str,
) -> Book | None:
    r"""Retrieve a book

    Returns one book by its ISBN-13.

    Args:
        isbn (str): (pattern: ^\d{13}$)

    Responses:
        200

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Book -- the parsed body of the 200 response, or None.
    """

    return (
        await asyncio_detailed(
        client=client,
        isbn=isbn,
        )
    ).parsed
