# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient
from ...models.book import Book
from ...types import Mismatch, Response, reading

PATH = '/books'
"""The path this module calls, before its `{...}` tokens are filled in."""

METHOD = 'post'
"""The HTTP method this module uses."""

SCHEMES = ('oauth2', 'basic')
"""The `securedBy:` schemes this operation accepts.

`security.py` holds the mechanics of each: which header carries the credential,
and what precedes it.
"""


def _kwargs(
    *,
    body: Book,
) -> dict[str, Any]:
    path = PATH

    params: dict[str, Any] = {}

    headers: dict[str, str] = {}
    headers['Content-Type'] = 'application/json'

    out: dict[str, Any] = {'method': METHOD, 'url': path}
    if params:
        out['params'] = params
    if headers:
        out['headers'] = headers
    out['json'] = body.to_dict()
    return out


def _parse(*, client: AuthenticatedClient, response: httpx.Response) -> Book | None:
    if response.status_code == 201:
        payload = response.json()
        return Book.from_dict(payload)
    if response.status_code in {400}:
        # Documented, and either carries no body or is not the one `sync`
        # answers with. The raw response is on the detailed variants.
        return None
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    return None


def _build(*, client: AuthenticatedClient, response: httpx.Response) -> Response[Book]:
    """The response, and whatever could be made of its body.

    Nothing a *payload* does gets out of here. A body that is not what the
    document describes -- a missing property, an unreadable date, HTML where
    JSON was promised -- lands in `mismatches`, and `content` still holds the
    bytes. Only `errors.UnexpectedStatus`, which the caller asked for, and a
    transport error, which is not about the payload, travel further.
    """
    parsed: Book | None = None
    with reading(strict=client.strict) as mismatches:
        try:
            parsed = _parse(client=client, response=response)
        except errors.ClientError:
            raise
        except Exception as unreadable:  # noqa: BLE001 - a payload may be anything at all
            mismatches.append(Mismatch('Book', '', f'{type(unreadable).__name__}: {unreadable}'))
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=parsed,
        mismatches=tuple(mismatches),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: Book,
) -> Response[Book]:
    r"""Add a book

    Adds one book to the catalogue and returns it with its identifier.

    Args:
        body (Book): sent as application/json.

    Responses:
        201: Created
        400: The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[Book] -- the status, the raw content and the parsed body.
    """

    response = client.get_httpx_client().request(**_kwargs(
        body=body,
    ))
    return _build(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: Book,
) -> Book | None:
    r"""Add a book

    Adds one book to the catalogue and returns it with its identifier.

    Args:
        body (Book): sent as application/json.

    Responses:
        201: Created
        400: The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Book -- the parsed body of the 201 response, or None.
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: Book,
) -> Response[Book]:
    r"""Add a book

    Adds one book to the catalogue and returns it with its identifier.

    Args:
        body (Book): sent as application/json.

    Responses:
        201: Created
        400: The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[Book] -- the status, the raw content and the parsed body.
    """

    response = await client.get_async_httpx_client().request(**_kwargs(
        body=body,
    ))
    return _build(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: Book,
) -> Book | None:
    r"""Add a book

    Adds one book to the catalogue and returns it with its identifier.

    Args:
        body (Book): sent as application/json.

    Responses:
        201: Created
        400: The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Book -- the parsed body of the 201 response, or None.
    """

    return (
        await asyncio_detailed(
        client=client,
        body=body,
        )
    ).parsed
