# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from typing import Annotated, Any

from pydantic import AfterValidator, BaseModel, Field

from ..runtime import unique_items
from .money import Money
from .review import Review


class Book(BaseModel):
    r"""One book in the catalogue.

    A book is identified by its `isbn`, which is the *thirteen*-digit form with no separators. Two
    fields are worth knowing about:

    * `price` is the current price; `priceHistory` is every price it has had, oldest first.
    * `related` is a list of other books, and may point back at this one.

    Attributes:
        title (str): The book's title as printed on the cover. (minLength: 1, maxLength: 200)
        isbn (str): The thirteen-digit ISBN, without separators. (pattern: ^\d{13}$, minLength: 13,
            maxLength: 13)
        price (Money): An amount and the currency it is denominated in.
        id_ (str)
        created_at (datetime.datetime)
        tags (list[str] | None): (maxItems: 10, uniqueItems: True)
        related (list[Book] | None)
        reviews (list[Review] | None): Up to twenty reviews, most recent first. (maxItems: 20)
        price_history (list[Money] | None): Every price this book has been sold at, oldest first.
        metadata (dict[str, Any] | None)
    """

    title: Annotated[str, Field(min_length=1, max_length=200)]
    isbn: Annotated[str, Field(min_length=13, max_length=13, pattern=r'^\d{13}$')]
    price: Money
    id_: Annotated[str, Field(alias='id')]
    created_at: Annotated[datetime.datetime, Field(alias='createdAt')]
    tags: Annotated[list[Annotated[str, Field(min_length=2, max_length=24, pattern=r'^[a-z][a-z0-9-]*$')]], Field(max_length=10), AfterValidator(unique_items)] | None = None
    related: list[Book] | None = None
    reviews: Annotated[list[Review], Field(max_length=20)] | None = None
    price_history: Annotated[list[Money] | None, Field(alias='priceHistory')] = None
    metadata: dict[str, Any] | None = None
