# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class Cat(BaseModel):
    r"""Cat

    Attributes:
        purrs (bool)
    """

    purrs: bool
