# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Chain(BaseModel):
    r"""Chain

    Attributes:
        next_ (Chain | None)
    """

    next_: Annotated[Chain | None, Field(alias='next')] = None
