# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class Curated(BaseModel):
    r"""Curated

    Attributes:
        curator (str)
    """

    curator: str
