# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from typing import Annotated

from pydantic import BaseModel, Field


class CuratedCollection(BaseModel):
    r"""A collection with identity and a curator, inherited from two types.

    Attributes:
        name (str)
        id_ (str)
        created_at (datetime.datetime)
        curator (str)
    """

    name: str
    id_: Annotated[str, Field(alias='id')]
    created_at: Annotated[datetime.datetime, Field(alias='createdAt')]
    curator: str
