# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from typing import Literal

from pydantic import BaseModel


class DeliveryQuery(BaseModel):
    r"""The whole query string as one type.

    RAML allows this instead of `queryParameters:`, never as well as it.

    Attributes:
        since (datetime.datetime): Only deliveries promised on or after this instant.
        status (Literal['pending', 'sent', 'delivered'] | None)
        city (str | None): Matched against the address, case-insensitively.
        carrier (Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon',
            'evri-standard'] | None): Only deliveries handed to this carrier.
    """

    since: datetime.datetime
    status: Literal['pending', 'sent', 'delivered'] | None = None
    city: str | None = None
    carrier: Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon', 'evri-standard'] | None = None
