# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import Field

Grams = Annotated[int, Field(ge=1, le=9223372036854775807)]
"""Whole grams.

Nothing here is sold by fractions of one.
"""
