# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class HasHome(BaseModel):
    r"""HasHome

    Attributes:
        home (str)
    """

    home: str
