# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class HomelyPetCat(BaseModel):
    r"""HomelyPetCat

    Attributes:
        home (str)
        purrs (bool)
    """

    home: str
    purrs: bool
