# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class HomelyPetDog(BaseModel):
    r"""HomelyPetDog

    Attributes:
        home (str)
        barks (bool)
    """

    home: str
    barks: bool
