# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from .homely_pet_cat import HomelyPetCat
from .homely_pet_dog import HomelyPetDog

HomelyPet = HomelyPetCat | HomelyPetDog
"""Either kind of pet, with a home required in both cases."""
