# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import Field

Isbn = Annotated[str, Field(min_length=13, max_length=13, pattern=r'^\d{13}$')]
"""The thirteen-digit ISBN, without separators."""
