# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class Line(BaseModel):
    r"""Line

    Attributes:
        description (str)
        amount (float)
    """

    description: str
    amount: float
