# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from .book import Book
from .delivery import Delivery
from .magazine import Magazine
from .money import Money
from .pamphlet import Pamphlet
from .publication import Publication
from .review import Review
from .shelf_slot import ShelfSlot


class Paged(BaseModel):
    r"""Paged

    Attributes:
        total (int)
        items (list[Book | Review | Money | list[ShelfSlot] | list[Money] | Publication | Magazine | Pamphlet | Delivery])
    """

    total: int
    items: list[Book | Review | Money | Annotated[list[ShelfSlot], Field(min_length=1)] | list[Money] | Publication | Magazine | Pamphlet | Delivery]
