# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class Pamphlet(BaseModel):
    r"""No `discriminatorValue`, so the value is the type's own name.

    Attributes:
        pages (int)
        kind (str)
        title (str)
    """

    pages: int
    kind: str
    title: str
