# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel


class Publication(BaseModel):
    r"""Everything the store sells.

    The `kind` property says which.

    Attributes:
        kind (str)
        title (str)
    """

    kind: str
    title: str
