# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from .author import Author


class Review(BaseModel):
    r"""One reader's verdict on a book.

    Attributes:
        rating (int): Stars, one to five. (minimum: 1, maximum: 5)
        author (Author)
        body (str | None)
    """

    rating: Annotated[int, Field(ge=1, le=5)]
    author: Author
    body: str | None = None
