# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field

from .book import Book


class ShelfSlot(BaseModel):
    r"""Shelf slot

    Attributes:
        position (int)
        book (Book): One book in the catalogue. A book is identified by its `isbn`, which is the
            *thirteen*-digit form with no separators. Two fields are worth knowing about: * `price`
            is the current price; `priceHistory` is every price it has had, oldest first. *
            `related` is a list of other books, and may point back at this one.
        note (str | None)
        locator (str | None): Where the physical copy sits, as one string. (pattern:
            ^(?:[A-Z]{2}-)?(?:AISLE|BAY|SHELF)-[0-9]{1,3}(?:\.[0-9]{1,2})?(?:-(?:LEFT|RIGHT|CENTRE))?(?:/[A-Za-z0-9_]{1,16})*$)
    """

    position: int
    book: Book
    note: str | None = None
    locator: Annotated[str, Field(pattern=r'^(?:[A-Z]{2}-)?(?:AISLE|BAY|SHELF)-[0-9]{1,3}(?:\.[0-9]{1,2})?(?:-(?:LEFT|RIGHT|CENTRE))?(?:/[A-Za-z0-9_]{1,16})*$')] | None = None
