# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import Field

from .shelf_slot import ShelfSlot

Shelf = Annotated[list[ShelfSlot], Field(min_length=1)]
"""An array whose items are declared inline rather than by name."""
