# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Barcode:
    r"""Barcode

    Attributes:
        symbology (Literal['EAN-13', 'UPC-A', 'CODE-128'])
        code (str): (minLength: 1)
    """

    symbology: Literal['EAN-13', 'UPC-A', 'CODE-128']
    code: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['symbology'] = self.symbology
        out['code'] = self.code
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Barcode:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        symbology = values.get('symbology', UNSET)
        code = values.get('code', UNSET)
        return cls(
            symbology=symbology if not isinstance(symbology, Unset) else absent('Barcode', 'symbology'),
            code=code if not isinstance(code, Unset) else absent('Barcode', 'code'),
        )
