# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent, as_list
from .money import Money
from .review import Review


@dataclass(slots=True)
class Book:
    r"""One book in the catalogue.

    A book is identified by its `isbn`, which is the *thirteen*-digit form with no separators. Two
    fields are worth knowing about:

    * `price` is the current price; `priceHistory` is every price it has had, oldest first.
    * `related` is a list of other books, and may point back at this one.

    Attributes:
        title (str): The book's title as printed on the cover. (minLength: 1, maxLength: 200)
        isbn (str): The thirteen-digit ISBN, without separators. (pattern: ^\d{13}$, minLength: 13,
            maxLength: 13)
        price (Money): An amount and the currency it is denominated in.
        id_ (str)
        created_at (datetime.datetime)
        tags (list[str]): (maxItems: 10, uniqueItems: True)
        related (list[Book])
        reviews (list[Review]): Up to twenty reviews, most recent first. (maxItems: 20)
        price_history (list[Money]): Every price this book has been sold at, oldest first.
        metadata (dict[str, Any])
    """

    title: str
    isbn: str
    price: Money
    id_: str
    created_at: datetime.datetime
    tags: list[str] | Unset = UNSET
    related: list[Book] | Unset = UNSET
    reviews: list[Review] | Unset = UNSET
    price_history: list[Money] | Unset = UNSET
    metadata: dict[str, Any] | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['title'] = self.title
        out['isbn'] = self.isbn
        out['price'] = self.price.to_dict()
        out['id'] = self.id_
        out['createdAt'] = self.created_at.isoformat()
        if not isinstance(self.tags, Unset):
            out['tags'] = self.tags
        if not isinstance(self.related, Unset):
            out['related'] = [_item.to_dict() for _item in self.related]
        if not isinstance(self.reviews, Unset):
            out['reviews'] = [_item.to_dict() for _item in self.reviews]
        if not isinstance(self.price_history, Unset):
            out['priceHistory'] = [_item.to_dict() for _item in self.price_history]
        if not isinstance(self.metadata, Unset):
            out['metadata'] = self.metadata
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Book:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        title = values.get('title', UNSET)
        isbn = values.get('isbn', UNSET)
        price = values.get('price', UNSET)
        id_ = values.get('id', UNSET)
        created_at = values.get('createdAt', UNSET)
        tags = values.get('tags', UNSET)
        related = values.get('related', UNSET)
        reviews = values.get('reviews', UNSET)
        price_history = values.get('priceHistory', UNSET)
        metadata = values.get('metadata', UNSET)
        return cls(
            title=title if not isinstance(title, Unset) else absent('Book', 'title'),
            isbn=isbn if not isinstance(isbn, Unset) else absent('Book', 'isbn'),
            price=(
                Money.from_dict(price)
                if not isinstance(price, Unset)
                else absent('Book', 'price')
            ),
            id_=id_ if not isinstance(id_, Unset) else absent('Book', 'id'),
            created_at=(
                datetime.datetime.fromisoformat(created_at)
                if not isinstance(created_at, Unset)
                else absent('Book', 'createdAt')
            ),
            tags=tags if not isinstance(tags, Unset) else UNSET,
            related=(
                [Book.from_dict(_item) for _item in as_list(related)]
                if not isinstance(related, Unset)
                else UNSET
            ),
            reviews=(
                [Review.from_dict(_item) for _item in as_list(reviews)]
                if not isinstance(reviews, Unset)
                else UNSET
            ),
            price_history=(
                [Money.from_dict(_item) for _item in as_list(price_history)]
                if not isinstance(price_history, Unset)
                else UNSET
            ),
            metadata=metadata if not isinstance(metadata, Unset) else UNSET,
        )
