# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset


@dataclass(slots=True)
class Chain:
    r"""Chain

    Attributes:
        next_ (Chain)
    """

    next_: Chain | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        if not isinstance(self.next_, Unset):
            out['next'] = self.next_.to_dict()
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Chain:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        next_ = values.get('next', UNSET)
        return cls(
            next_=(
                Chain.from_dict(next_)
                if not isinstance(next_, Unset)
                else UNSET
            ),
        )
