# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Entity:
    r"""Entity

    Attributes:
        id_ (str)
        created_at (datetime.datetime)
    """

    id_: str
    created_at: datetime.datetime

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['id'] = self.id_
        out['createdAt'] = self.created_at.isoformat()
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Entity:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        id_ = values.get('id', UNSET)
        created_at = values.get('createdAt', UNSET)
        return cls(
            id_=id_ if not isinstance(id_, Unset) else absent('Entity', 'id'),
            created_at=(
                datetime.datetime.fromisoformat(created_at)
                if not isinstance(created_at, Unset)
                else absent('Entity', 'createdAt')
            ),
        )
