# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent, as_list, to_json
from .book import Book
from .delivery import Delivery
from .magazine import Magazine
from .money import Money
from .pamphlet import Pamphlet
from .publication import Publication
from .review import Review
from .shelf_slot import ShelfSlot


@dataclass(slots=True)
class Paged:
    r"""Paged

    Attributes:
        total (int)
        items (list[Book | Review | Money | list[ShelfSlot] | list[Money] | Publication | Magazine | Pamphlet | Delivery])
    """

    total: int
    items: list[Book | Review | Money | list[ShelfSlot] | list[Money] | Publication | Magazine | Pamphlet | Delivery]

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['total'] = self.total
        out['items'] = [to_json(_item) for _item in self.items]
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Paged:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        total = values.get('total', UNSET)
        items = values.get('items', UNSET)
        return cls(
            total=total if not isinstance(total, Unset) else absent('Paged', 'total'),
            items=(
                [(_item if isinstance(_item, list) else (Book.from_dict(_item) if 'createdAt' in _item else (Review.from_dict(_item) if 'author' in _item else (Money.from_dict(_item) if 'amount' in _item else (Magazine.from_dict(_item) if _item.get('kind') == 'monthly' else (Pamphlet.from_dict(_item) if 'pages' in _item else (Delivery.from_dict(_item) if 'address' in _item else Publication.from_dict(_item)))))))) for _item in as_list(items)]
                if not isinstance(items, Unset)
                else absent('Paged', 'items')
            ),
        )
