# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Publication:
    r"""Everything the store sells.

    The `kind` property says which.

    Attributes:
        kind (str)
        title (str)
    """

    kind: str
    title: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['kind'] = self.kind
        out['title'] = self.title
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Publication:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        kind = values.get('kind', UNSET)
        title = values.get('title', UNSET)
        return cls(
            kind=kind if not isinstance(kind, Unset) else absent('Publication', 'kind'),
            title=title if not isinstance(title, Unset) else absent('Publication', 'title'),
        )
