# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent
from .author import Author


@dataclass(slots=True)
class Review:
    r"""One reader's verdict on a book.

    Attributes:
        rating (int): Stars, one to five. (minimum: 1, maximum: 5)
        author (Author)
        body (str)
    """

    rating: int
    author: Author
    body: str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['rating'] = self.rating
        out['author'] = self.author.to_dict()
        if not isinstance(self.body, Unset):
            out['body'] = self.body
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Review:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        rating = values.get('rating', UNSET)
        author = values.get('author', UNSET)
        body = values.get('body', UNSET)
        return cls(
            rating=rating if not isinstance(rating, Unset) else absent('Review', 'rating'),
            author=(
                Author.from_dict(author)
                if not isinstance(author, Unset)
                else absent('Review', 'author')
            ),
            body=body if not isinstance(body, Unset) else UNSET,
        )
