# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent
from .book import Book


@dataclass(slots=True)
class ShelfSlot:
    r"""Shelf slot

    Attributes:
        position (int)
        book (Book): One book in the catalogue. A book is identified by its `isbn`, which is the
            *thirteen*-digit form with no separators. Two fields are worth knowing about: * `price`
            is the current price; `priceHistory` is every price it has had, oldest first. *
            `related` is a list of other books, and may point back at this one.
        note (str)
        locator (str): Where the physical copy sits, as one string. (pattern:
            ^(?:[A-Z]{2}-)?(?:AISLE|BAY|SHELF)-[0-9]{1,3}(?:\.[0-9]{1,2})?(?:-(?:LEFT|RIGHT|CENTRE))?(?:/[A-Za-z0-9_]{1,16})*$)
    """

    position: int
    book: Book
    note: str | Unset = UNSET
    locator: str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['position'] = self.position
        out['book'] = self.book.to_dict()
        if not isinstance(self.note, Unset):
            out['note'] = self.note
        if not isinstance(self.locator, Unset):
            out['locator'] = self.locator
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> ShelfSlot:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        position = values.get('position', UNSET)
        book = values.get('book', UNSET)
        note = values.get('note', UNSET)
        locator = values.get('locator', UNSET)
        return cls(
            position=position if not isinstance(position, Unset) else absent('ShelfSlot', 'position'),
            book=(
                Book.from_dict(book)
                if not isinstance(book, Unset)
                else absent('ShelfSlot', 'book')
            ),
            note=note if not isinstance(note, Unset) else UNSET,
            locator=locator if not isinstance(locator, Unset) else UNSET,
        )
