# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""Every type the document declares, and the anonymous ones they contain.

**A model is its JSON.** Each is a `TypedDict` keyed by the property names as
the document spells them -- `payload['@odata.type']`, `payload['class']` -- so
no name is invented and no value is converted. A request body is a dict
literal; a response body is what `response.json()` returned, typed. A date is
the string the server sent.

Beside each model is a reader, `read_<model>(value)`, which checks a decoded
value against the document and hands back the same value.

**RAML inheritance is not `TypedDict` inheritance**: the effective tree merged
the hierarchy before this package saw it, and `type: [A, B]` has no MRO while a
subtype that narrows a property's type has no legal override. So a subtype
carries its supertype's properties and is a type of its own. Where the document
states a `discriminatorValue:`, the model's discriminator key is that value's
`Literal`, and the module holds it as `DISCRIMINATOR`.

**A reader is lenient, and that is the whole of what it means:**

* a property the document does not describe is kept, not checked;
* a property the document *requires* and the payload does not carry is absent
  from the dictionary -- read it with `.get` -- and reaches
  `Response.mismatches`, rather than taking the whole response with it;
* `Client(strict=True)` turns the second one back into `errors.UnexpectedPayload`.

A value's *type* is not checked. Enforcing one here would restate a rule of the
RAML language on this side of the boundary, and the client could not say whether
the server or the document is the one that is wrong.
"""

from __future__ import annotations

from .address import Address, read_address
from .amount import Amount, read_amount
from .anything import Anything
from .author import Author, read_author
from .barcode import Barcode, read_barcode
from .book import Book, read_book
from .cat import Cat, read_cat
from .chain import Chain, read_chain
from .curated import Curated, read_curated
from .curated_collection import CuratedCollection, read_curated_collection
from .delivery import Delivery, read_delivery
from .delivery_query import DeliveryQuery, read_delivery_query
from .dog import Dog, read_dog
from .entity import Entity, read_entity
from .grams import Grams
from .has_home import HasHome, read_has_home
from .homely_pet import HomelyPet
from .homely_pet_cat import HomelyPetCat, read_homely_pet_cat
from .homely_pet_dog import HomelyPetDog, read_homely_pet_dog
from .invoice import Invoice, read_invoice
from .invoice_json import InvoiceJson, read_invoice_json
from .isbn import Isbn
from .line import Line, read_line
from .magazine import Magazine, read_magazine
from .money import Money, read_money
from .page import Page, read_page
from .paged import Paged, read_paged
from .pamphlet import Pamphlet, read_pamphlet
from .parcel import Parcel, read_parcel
from .payload import Payload
from .prices import Prices
from .publication import Publication, read_publication
from .review import Review, read_review
from .search import Search
from .shelf import Shelf
from .shelf_slot import ShelfSlot, read_shelf_slot
from .tolerance import Tolerance

__all__ = [
    'Address',
    'Amount',
    'Anything',
    'Author',
    'Barcode',
    'Book',
    'Cat',
    'Chain',
    'Curated',
    'CuratedCollection',
    'Delivery',
    'DeliveryQuery',
    'Dog',
    'Entity',
    'Grams',
    'HasHome',
    'HomelyPet',
    'HomelyPetCat',
    'HomelyPetDog',
    'Invoice',
    'InvoiceJson',
    'Isbn',
    'Line',
    'Magazine',
    'Money',
    'Page',
    'Paged',
    'Pamphlet',
    'Parcel',
    'Payload',
    'Prices',
    'Publication',
    'Review',
    'Search',
    'Shelf',
    'ShelfSlot',
    'Tolerance',
    'read_address',
    'read_amount',
    'read_author',
    'read_barcode',
    'read_book',
    'read_cat',
    'read_chain',
    'read_curated',
    'read_curated_collection',
    'read_delivery',
    'read_delivery_query',
    'read_dog',
    'read_entity',
    'read_has_home',
    'read_homely_pet_cat',
    'read_homely_pet_dog',
    'read_invoice',
    'read_invoice_json',
    'read_line',
    'read_magazine',
    'read_money',
    'read_page',
    'read_paged',
    'read_pamphlet',
    'read_parcel',
    'read_publication',
    'read_review',
    'read_shelf_slot',
]
