# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict, require

Address = TypedDict(
    'Address',
    {
        'line1': 'str',
        'city': 'str',
        'postcode': 'str',
        'country': 'str',
        'line2': 'NotRequired[str]',
    },
)
r"""Where a physical thing is sent.

Keys:
    line1 (str)
    city (str)
    postcode (str): (pattern: ^[A-Z0-9 ]{4,10}$)
    country (str): An ISO 3166-1 alpha-2 code. (minLength: 2, maxLength: 2)
    line2 (str)
"""


def read_address(source: Any) -> Address:
    """Check a decoded `Address` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Address', ('line1', 'city', 'postcode', 'country'))
    return cast(Address, values)
