# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, Literal, TypedDict, cast

from ..types import as_dict, require

Amount = TypedDict(
    'Amount',
    {
        'minor': 'int',
        'currency': "Literal['USD', 'EUR', 'GBP']",
    },
)
r"""A sum of money, in the smallest unit of its currency.

Keys:
    minor (int): Pence, cents, or the equivalent.
    currency (Literal['USD', 'EUR', 'GBP'])
"""


def read_amount(source: Any) -> Amount:
    """Check a decoded `Amount` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Amount', ('minor', 'currency'))
    return cast(Amount, values)
