# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from .anything import Anything

AnythingAlias = Anything
"""Everything this API will accept in a body, as one type."""
