# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Author:
    r"""Author

    Attributes:
        name (str)
        verified (bool): Default: False.
    """

    name: str
    verified: bool

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['name'] = self.name
        out['verified'] = self.verified
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Author:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        name = values.get('name', UNSET)
        verified = values.get('verified', UNSET)
        return cls(
            name=name if not isinstance(name, Unset) else absent('Author', 'name'),
            verified=verified if not isinstance(verified, Unset) else absent('Author', 'verified'),
        )
