# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Author = TypedDict(
    'Author',
    {
        'name': 'str',
        'verified': 'bool',
    },
)
r"""Author

Keys:
    name (str)
    verified (bool): Default: False.
"""


def read_author(source: Any) -> Author:
    """Check a decoded `Author` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Author', ('name', 'verified'))
    return cast(Author, values)
