# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, Literal, TypedDict, cast

from ..types import as_dict, require

Barcode = TypedDict(
    'Barcode',
    {
        'symbology': "Literal['EAN-13', 'UPC-A', 'CODE-128']",
        'code': 'str',
    },
)
r"""Barcode

Keys:
    symbology (Literal['EAN-13', 'UPC-A', 'CODE-128'])
    code (str): (minLength: 1)
"""


def read_barcode(source: Any) -> Barcode:
    """Check a decoded `Barcode` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Barcode', ('symbology', 'code'))
    return cast(Barcode, values)
