# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import DateTime, as_dict, as_list, each, require
from .money import Money, read_money
from .review import Review, read_review

Book = TypedDict(
    'Book',
    {
        'title': 'str',
        'isbn': 'str',
        'price': 'Money',
        'id': 'str',
        'createdAt': 'DateTime',
        'tags': 'NotRequired[list[str]]',
        'related': 'NotRequired[list[Book]]',
        'reviews': 'NotRequired[list[Review]]',
        'priceHistory': 'NotRequired[list[Money]]',
        'metadata': 'NotRequired[dict[str, Any]]',
    },
)
r"""One book in the catalogue.

A book is identified by its `isbn`, which is the *thirteen*-digit form with no separators. Two
fields are worth knowing about:

* `price` is the current price; `priceHistory` is every price it has had, oldest first.
* `related` is a list of other books, and may point back at this one.

Keys:
    title (str): The book's title as printed on the cover. (minLength: 1, maxLength: 200)
    isbn (str): The thirteen-digit ISBN, without separators. (pattern: ^\d{13}$, minLength: 13,
        maxLength: 13)
    price (Money): An amount and the currency it is denominated in.
    id (str)
    createdAt (DateTime)
    tags (list[str]): (maxItems: 10, uniqueItems: True)
    related (list[Book])
    reviews (list[Review]): Up to twenty reviews, most recent first. (maxItems: 20)
    priceHistory (list[Money]): Every price this book has been sold at, oldest first.
    metadata (dict[str, Any])
"""


def read_book(source: Any) -> Book:
    """Check a decoded `Book` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Book', ('title', 'isbn', 'price', 'id', 'createdAt'))
    if 'price' in values:
        read_money(values['price'])
    if 'related' in values:
        each(read_book(_item) for _item in as_list(values['related']))
    if 'reviews' in values:
        each(read_review(_item) for _item in as_list(values['reviews']))
    if 'priceHistory' in values:
        each(read_money(_item) for _item in as_list(values['priceHistory']))
    return cast(Book, values)
