# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Cat = TypedDict(
    'Cat',
    {
        'purrs': 'bool',
    },
)
r"""Cat

Keys:
    purrs (bool)
"""


def read_cat(source: Any) -> Cat:
    """Check a decoded `Cat` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Cat', ('purrs',))
    return cast(Cat, values)
