# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict

Chain = TypedDict(
    'Chain',
    {
        'next': 'NotRequired[Chain]',
    },
)
r"""Chain

Keys:
    next (Chain)
"""


def read_chain(source: Any) -> Chain:
    """Check a decoded `Chain` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    if 'next' in values:
        read_chain(values['next'])
    return cast(Chain, values)
