# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class CuratedCollection:
    r"""A collection with identity and a curator, inherited from two types.

    Attributes:
        name (str)
        id_ (str)
        created_at (datetime.datetime)
        curator (str)
    """

    name: str
    id_: str
    created_at: datetime.datetime
    curator: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['name'] = self.name
        out['id'] = self.id_
        out['createdAt'] = self.created_at.isoformat()
        out['curator'] = self.curator
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> CuratedCollection:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        name = values.get('name', UNSET)
        id_ = values.get('id', UNSET)
        created_at = values.get('createdAt', UNSET)
        curator = values.get('curator', UNSET)
        return cls(
            name=name if not isinstance(name, Unset) else absent('CuratedCollection', 'name'),
            id_=id_ if not isinstance(id_, Unset) else absent('CuratedCollection', 'id'),
            created_at=(
                datetime.datetime.fromisoformat(created_at)
                if not isinstance(created_at, Unset)
                else absent('CuratedCollection', 'createdAt')
            ),
            curator=curator if not isinstance(curator, Unset) else absent('CuratedCollection', 'curator'),
        )
