# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import DateTime, as_dict, require

CuratedCollection = TypedDict(
    'CuratedCollection',
    {
        'name': 'str',
        'id': 'str',
        'createdAt': 'DateTime',
        'curator': 'str',
    },
)
r"""A collection with identity and a curator, inherited from two types.

Keys:
    name (str)
    id (str)
    createdAt (DateTime)
    curator (str)
"""


def read_curated_collection(source: Any) -> CuratedCollection:
    """Check a decoded `CuratedCollection` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'CuratedCollection', ('name', 'id', 'createdAt', 'curator'))
    return cast(CuratedCollection, values)
