# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Curated = TypedDict(
    'Curated',
    {
        'curator': 'str',
    },
)
r"""Curated

Keys:
    curator (str)
"""


def read_curated(source: Any) -> Curated:
    """Check a decoded `Curated` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Curated', ('curator',))
    return cast(Curated, values)
