# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Curated:
    r"""Curated

    Attributes:
        curator (str)
    """

    curator: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['curator'] = self.curator
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Curated:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        curator = values.get('curator', UNSET)
        return cls(
            curator=curator if not isinstance(curator, Unset) else absent('Curated', 'curator'),
        )
