# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict, cast

from ..types import DateTime, as_dict, require

DeliveryQuery = TypedDict(
    'DeliveryQuery',
    {
        'since': 'DateTime',
        'status': "NotRequired[Literal['pending', 'sent', 'delivered']]",
        'city': 'NotRequired[str]',
        'carrier': "NotRequired[Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon', 'evri-standard']]",
    },
)
r"""The whole query string as one type.

RAML allows this instead of `queryParameters:`, never as well as it.

Keys:
    since (DateTime): Only deliveries promised on or after this instant.
    status (Literal['pending', 'sent', 'delivered'])
    city (str): Matched against the address, case-insensitively.
    carrier (Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon',
        'evri-standard']): Only deliveries handed to this carrier.
"""


def read_delivery_query(source: Any) -> DeliveryQuery:
    """Check a decoded `DeliveryQuery` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'DeliveryQuery', ('since',))
    return cast(DeliveryQuery, values)
