# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent
from .address import Address
from .parcel import Parcel


@dataclass(slots=True)
class Delivery:
    r"""Where an order goes, and when it was promised.

    Attributes:
        address (Address): Where a physical thing is sent.
        promised_for (datetime.datetime)
        parcel (Parcel): What a delivery is packed in.
    """

    address: Address
    promised_for: datetime.datetime
    parcel: Parcel | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['address'] = self.address.to_dict()
        out['promisedFor'] = self.promised_for.isoformat()
        if not isinstance(self.parcel, Unset):
            out['parcel'] = self.parcel.to_dict()
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Delivery:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        address = values.get('address', UNSET)
        promised_for = values.get('promisedFor', UNSET)
        parcel = values.get('parcel', UNSET)
        return cls(
            address=(
                Address.from_dict(address)
                if not isinstance(address, Unset)
                else absent('Delivery', 'address')
            ),
            promised_for=(
                datetime.datetime.fromisoformat(promised_for)
                if not isinstance(promised_for, Unset)
                else absent('Delivery', 'promisedFor')
            ),
            parcel=(
                Parcel.from_dict(parcel)
                if not isinstance(parcel, Unset)
                else UNSET
            ),
        )
