# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import DateTime, as_dict, require
from .address import Address, read_address
from .parcel import Parcel, read_parcel

Delivery = TypedDict(
    'Delivery',
    {
        'address': 'Address',
        'promisedFor': 'DateTime',
        'parcel': 'NotRequired[Parcel]',
    },
)
r"""Where an order goes, and when it was promised.

Keys:
    address (Address): Where a physical thing is sent.
    promisedFor (DateTime)
    parcel (Parcel): What a delivery is packed in.
"""


def read_delivery(source: Any) -> Delivery:
    """Check a decoded `Delivery` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Delivery', ('address', 'promisedFor'))
    if 'address' in values:
        read_address(values['address'])
    if 'parcel' in values:
        read_parcel(values['parcel'])
    return cast(Delivery, values)
