# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class DeliveryQuery:
    r"""The whole query string as one type.

    RAML allows this instead of `queryParameters:`, never as well as it.

    Attributes:
        since (datetime.datetime): Only deliveries promised on or after this instant.
        status (Literal['pending', 'sent', 'delivered'])
        city (str): Matched against the address, case-insensitively.
        carrier (Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon',
            'evri-standard']): Only deliveries handed to this carrier.
    """

    since: datetime.datetime
    status: Literal['pending', 'sent', 'delivered'] | Unset = UNSET
    city: str | Unset = UNSET
    carrier: Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon', 'evri-standard'] | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['since'] = self.since.isoformat()
        if not isinstance(self.status, Unset):
            out['status'] = self.status
        if not isinstance(self.city, Unset):
            out['city'] = self.city
        if not isinstance(self.carrier, Unset):
            out['carrier'] = self.carrier
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> DeliveryQuery:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        since = values.get('since', UNSET)
        status = values.get('status', UNSET)
        city = values.get('city', UNSET)
        carrier = values.get('carrier', UNSET)
        return cls(
            since=(
                datetime.datetime.fromisoformat(since)
                if not isinstance(since, Unset)
                else absent('DeliveryQuery', 'since')
            ),
            status=status if not isinstance(status, Unset) else UNSET,
            city=city if not isinstance(city, Unset) else UNSET,
            carrier=carrier if not isinstance(carrier, Unset) else UNSET,
        )
