# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Dog:
    r"""Dog

    Attributes:
        barks (bool)
    """

    barks: bool

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['barks'] = self.barks
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Dog:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        barks = values.get('barks', UNSET)
        return cls(
            barks=barks if not isinstance(barks, Unset) else absent('Dog', 'barks'),
        )
