# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Dog = TypedDict(
    'Dog',
    {
        'barks': 'bool',
    },
)
r"""Dog

Keys:
    barks (bool)
"""


def read_dog(source: Any) -> Dog:
    """Check a decoded `Dog` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Dog', ('barks',))
    return cast(Dog, values)
