# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import DateTime, as_dict, require

Entity = TypedDict(
    'Entity',
    {
        'id': 'str',
        'createdAt': 'DateTime',
    },
)
r"""Entity

Keys:
    id (str)
    createdAt (DateTime)
"""


def read_entity(source: Any) -> Entity:
    """Check a decoded `Entity` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Entity', ('id', 'createdAt'))
    return cast(Entity, values)
