# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

HasHome = TypedDict(
    'HasHome',
    {
        'home': 'str',
    },
)
r"""HasHome

Keys:
    home (str)
"""


def read_has_home(source: Any) -> HasHome:
    """Check a decoded `HasHome` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'HasHome', ('home',))
    return cast(HasHome, values)
