# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

HomelyPetCat = TypedDict(
    'HomelyPetCat',
    {
        'home': 'str',
        'purrs': 'bool',
    },
)
r"""HomelyPetCat

Keys:
    home (str)
    purrs (bool)
"""


def read_homely_pet_cat(source: Any) -> HomelyPetCat:
    """Check a decoded `HomelyPetCat` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'HomelyPetCat', ('home', 'purrs'))
    return cast(HomelyPetCat, values)
