# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class HomelyPetCat:
    r"""HomelyPetCat

    Attributes:
        home (str)
        purrs (bool)
    """

    home: str
    purrs: bool

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['home'] = self.home
        out['purrs'] = self.purrs
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> HomelyPetCat:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        home = values.get('home', UNSET)
        purrs = values.get('purrs', UNSET)
        return cls(
            home=home if not isinstance(home, Unset) else absent('HomelyPetCat', 'home'),
            purrs=purrs if not isinstance(purrs, Unset) else absent('HomelyPetCat', 'purrs'),
        )
