# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

HomelyPetDog = TypedDict(
    'HomelyPetDog',
    {
        'home': 'str',
        'barks': 'bool',
    },
)
r"""HomelyPetDog

Keys:
    home (str)
    barks (bool)
"""


def read_homely_pet_dog(source: Any) -> HomelyPetDog:
    """Check a decoded `HomelyPetDog` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'HomelyPetDog', ('home', 'barks'))
    return cast(HomelyPetDog, values)
