# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class HomelyPetDog:
    r"""HomelyPetDog

    Attributes:
        home (str)
        barks (bool)
    """

    home: str
    barks: bool

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['home'] = self.home
        out['barks'] = self.barks
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> HomelyPetDog:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        home = values.get('home', UNSET)
        barks = values.get('barks', UNSET)
        return cls(
            home=home if not isinstance(home, Unset) else absent('HomelyPetDog', 'home'),
            barks=barks if not isinstance(barks, Unset) else absent('HomelyPetDog', 'barks'),
        )
