# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent, as_list
from .amount import Amount
from .line import Line


@dataclass(slots=True)
class Invoice:
    r"""A type declared by JSON Schema rather than by RAML.

    Attributes:
        number (str): The invoice number, as printed. (pattern: ^INV-[0-9]{6}$)
        total (float): The amount due, in the currency of the account. (minimum: 0, multipleOf:
            0.01)
        settled (Amount): A sum of money, in the smallest unit of its currency.
        paid (bool): Default: False.
        lines (list[Line]): (minItems: 1)
    """

    number: str
    total: float
    settled: Amount | Unset = UNSET
    paid: bool | Unset = UNSET
    lines: list[Line] | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['number'] = self.number
        out['total'] = self.total
        if not isinstance(self.settled, Unset):
            out['settled'] = self.settled.to_dict()
        if not isinstance(self.paid, Unset):
            out['paid'] = self.paid
        if not isinstance(self.lines, Unset):
            out['lines'] = [_item.to_dict() for _item in self.lines]
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Invoice:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        number = values.get('number', UNSET)
        total = values.get('total', UNSET)
        settled = values.get('settled', UNSET)
        paid = values.get('paid', UNSET)
        lines = values.get('lines', UNSET)
        return cls(
            number=number if not isinstance(number, Unset) else absent('Invoice', 'number'),
            total=total if not isinstance(total, Unset) else absent('Invoice', 'total'),
            settled=(
                Amount.from_dict(settled)
                if not isinstance(settled, Unset)
                else UNSET
            ),
            paid=paid if not isinstance(paid, Unset) else UNSET,
            lines=(
                [Line.from_dict(_item) for _item in as_list(lines)]
                if not isinstance(lines, Unset)
                else UNSET
            ),
        )
