# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict, as_list, each, require
from .amount import Amount, read_amount
from .line import Line, read_line

Invoice = TypedDict(
    'Invoice',
    {
        'number': 'str',
        'total': 'float',
        'settled': 'NotRequired[Amount]',
        'paid': 'NotRequired[bool]',
        'lines': 'NotRequired[list[Line]]',
    },
)
r"""A type declared by JSON Schema rather than by RAML.

Keys:
    number (str): The invoice number, as printed. (pattern: ^INV-[0-9]{6}$)
    total (float): The amount due, in the currency of the account. (minimum: 0, multipleOf: 0.01)
    settled (Amount): A sum of money, in the smallest unit of its currency.
    paid (bool): Default: False.
    lines (list[Line]): (minItems: 1)
"""


def read_invoice(source: Any) -> Invoice:
    """Check a decoded `Invoice` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Invoice', ('number', 'total'))
    if 'settled' in values:
        read_amount(values['settled'])
    if 'lines' in values:
        each(read_line(_item) for _item in as_list(values['lines']))
    return cast(Invoice, values)
