# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Line = TypedDict(
    'Line',
    {
        'description': 'str',
        'amount': 'float',
    },
)
r"""Line

Keys:
    description (str)
    amount (float)
"""


def read_line(source: Any) -> Line:
    """Check a decoded `Line` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Line', ('description', 'amount'))
    return cast(Line, values)
