# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent

DISCRIMINATOR = ('kind', 'monthly')
"""The property this type is told apart by, and the value that means this type.

Models are flat, so switch on this where you would otherwise use `isinstance`.
"""


@dataclass(slots=True)
class Magazine:
    r"""A periodical, told apart by `kind: monthly`.

    Attributes:
        issue (int)
        kind (str)
        title (str)
    """

    issue: int
    kind: str
    title: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['issue'] = self.issue
        out['kind'] = self.kind
        out['title'] = self.title
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Magazine:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        issue = values.get('issue', UNSET)
        kind = values.get('kind', UNSET)
        title = values.get('title', UNSET)
        return cls(
            issue=issue if not isinstance(issue, Unset) else absent('Magazine', 'issue'),
            kind=kind if not isinstance(kind, Unset) else absent('Magazine', 'kind'),
            title=title if not isinstance(title, Unset) else absent('Magazine', 'title'),
        )
