# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, Literal, TypedDict, cast

from ..types import as_dict, require

DISCRIMINATOR = ('kind', 'monthly')
"""The property this type is told apart by, and the value that means this type.

Models are flat, so switch on this where you would otherwise use `isinstance`.
"""

Magazine = TypedDict(
    'Magazine',
    {
        'issue': 'int',
        'kind': "Literal['monthly']",
        'title': 'str',
    },
)
r"""A periodical, told apart by `kind: monthly`.

Keys:
    issue (int)
    kind (Literal['monthly'])
    title (str)
"""


def read_magazine(source: Any) -> Magazine:
    """Check a decoded `Magazine` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Magazine', ('issue', 'kind', 'title'))
    return cast(Magazine, values)
