# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, Literal, TypedDict, cast

from ..types import as_dict, require

Money = TypedDict(
    'Money',
    {
        'amount': 'float',
        'currency': "Literal['USD', 'EUR', 'GBP']",
    },
)
r"""An amount and the currency it is denominated in.

Keys:
    amount (float): (minimum: 0, multipleOf: 0.01)
    currency (Literal['USD', 'EUR', 'GBP'])
"""


def read_money(source: Any) -> Money:
    """Check a decoded `Money` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Money', ('amount', 'currency'))
    return cast(Money, values)
