# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, as_list, each, require
from .book import Book, read_book
from .delivery import Delivery, read_delivery
from .magazine import Magazine, read_magazine
from .money import Money, read_money
from .pamphlet import Pamphlet, read_pamphlet
from .publication import Publication, read_publication
from .review import Review, read_review
from .shelf_slot import ShelfSlot

Paged = TypedDict(
    'Paged',
    {
        'total': 'int',
        'items': 'list[Book | Review | Money | list[ShelfSlot] | list[Money] | Publication | Magazine | Pamphlet | Delivery]',
    },
)
r"""Paged

Keys:
    total (int)
    items (list[Book | Review | Money | list[ShelfSlot] | list[Money] | Publication | Magazine | Pamphlet | Delivery])
"""


def read_paged(source: Any) -> Paged:
    """Check a decoded `Paged` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Paged', ('total', 'items'))
    if 'items' in values:
        each((_item if isinstance(_item, list) else (read_book(_item) if 'createdAt' in _item else (read_review(_item) if 'author' in _item else (read_money(_item) if 'amount' in _item else (read_magazine(_item) if _item.get('kind') == 'monthly' else (read_pamphlet(_item) if 'pages' in _item else (read_delivery(_item) if 'address' in _item else read_publication(_item)))))))) for _item in as_list(values['items']))
    return cast(Paged, values)
