# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Page = TypedDict(
    'Page',
    {
        'total': 'int',
        'offset': 'int',
        'limit': 'int',
    },
)
r"""The envelope every paged collection is returned in.

`total` counts the whole collection, not the page.

Keys:
    total (int)
    offset (int)
    limit (int)
"""


def read_page(source: Any) -> Page:
    """Check a decoded `Page` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Page', ('total', 'offset', 'limit'))
    return cast(Page, values)
