# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Pamphlet:
    r"""No `discriminatorValue`, so the value is the type's own name.

    Attributes:
        pages (int)
        kind (str)
        title (str)
    """

    pages: int
    kind: str
    title: str

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['pages'] = self.pages
        out['kind'] = self.kind
        out['title'] = self.title
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Pamphlet:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        pages = values.get('pages', UNSET)
        kind = values.get('kind', UNSET)
        title = values.get('title', UNSET)
        return cls(
            pages=pages if not isinstance(pages, Unset) else absent('Pamphlet', 'pages'),
            kind=kind if not isinstance(kind, Unset) else absent('Pamphlet', 'kind'),
            title=title if not isinstance(title, Unset) else absent('Pamphlet', 'title'),
        )
