# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Pamphlet = TypedDict(
    'Pamphlet',
    {
        'pages': 'int',
        'kind': 'str',
        'title': 'str',
    },
)
r"""No `discriminatorValue`, so the value is the type's own name.

Keys:
    pages (int)
    kind (str)
    title (str)
"""


def read_pamphlet(source: Any) -> Pamphlet:
    """Check a decoded `Pamphlet` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Pamphlet', ('pages', 'kind', 'title'))
    return cast(Pamphlet, values)
