# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict, require

Parcel = TypedDict(
    'Parcel',
    {
        'weight': 'int',
        'trackingNumber': 'int',
        'tolerance': 'NotRequired[float]',
    },
)
r"""What a delivery is packed in.

Keys:
    weight (int): Whole grams. Nothing here is sold by fractions of one. (minimum: 1, maximum:
        9223372036854775807)
    trackingNumber (int): The carrier's own identifier, which is a signed 64-bit integer.
    tolerance (float): The bounds a scale is allowed to be out by, written at the limits of a 64-bit
        float because that is where a reader finds out whether the documentation survived the trip.
        (minimum: 2.2250738585072014E-308, maximum: 1.7976931348623157E+308, multipleOf: 0.000001)
"""


def read_parcel(source: Any) -> Parcel:
    """Check a decoded `Parcel` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Parcel', ('weight', 'trackingNumber'))
    return cast(Parcel, values)
