# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Parcel:
    r"""What a delivery is packed in.

    Attributes:
        weight (int): Whole grams. Nothing here is sold by fractions of one. (minimum: 1, maximum:
            9223372036854775807)
        tracking_number (int): The carrier's own identifier, which is a signed 64-bit integer.
        tolerance (float): The bounds a scale is allowed to be out by, written at the limits of a
            64-bit float because that is where a reader finds out whether the documentation survived
            the trip. (minimum: 2.2250738585072014E-308, maximum: 1.7976931348623157E+308,
            multipleOf: 0.000001)
    """

    weight: int
    tracking_number: int
    tolerance: float | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['weight'] = self.weight
        out['trackingNumber'] = self.tracking_number
        if not isinstance(self.tolerance, Unset):
            out['tolerance'] = self.tolerance
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Parcel:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        weight = values.get('weight', UNSET)
        tracking_number = values.get('trackingNumber', UNSET)
        tolerance = values.get('tolerance', UNSET)
        return cls(
            weight=weight if not isinstance(weight, Unset) else absent('Parcel', 'weight'),
            tracking_number=tracking_number if not isinstance(tracking_number, Unset) else absent('Parcel', 'trackingNumber'),
            tolerance=tolerance if not isinstance(tolerance, Unset) else UNSET,
        )
