# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from .money import Money

Prices = list[Money]
"""Every price this book has been sold at, oldest first."""
