# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, TypedDict, cast

from ..types import as_dict, require

Publication = TypedDict(
    'Publication',
    {
        'kind': 'str',
        'title': 'str',
    },
)
r"""Everything the store sells.

The `kind` property says which.

Keys:
    kind (str)
    title (str)
"""


def read_publication(source: Any) -> Publication:
    """Check a decoded `Publication` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Publication', ('kind', 'title'))
    return cast(Publication, values)
