# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict, require
from .author import Author, read_author

Review = TypedDict(
    'Review',
    {
        'rating': 'int',
        'author': 'Author',
        'body': 'NotRequired[str]',
    },
)
r"""One reader's verdict on a book.

Keys:
    rating (int): Stars, one to five. (minimum: 1, maximum: 5)
    author (Author)
    body (str)
"""


def read_review(source: Any) -> Review:
    """Check a decoded `Review` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'Review', ('rating', 'author'))
    if 'author' in values:
        read_author(values['author'])
    return cast(Review, values)
