# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Any, NotRequired, TypedDict, cast

from ..types import as_dict, require
from .book import Book, read_book

ShelfSlot = TypedDict(
    'ShelfSlot',
    {
        'position': 'int',
        'book': 'Book',
        'note': 'NotRequired[str]',
        'locator': 'NotRequired[str]',
    },
)
r"""Shelf slot

Keys:
    position (int)
    book (Book): One book in the catalogue. A book is identified by its `isbn`, which is the
        *thirteen*-digit form with no separators. Two fields are worth knowing about: * `price` is
        the current price; `priceHistory` is every price it has had, oldest first. * `related` is a
        list of other books, and may point back at this one.
    note (str)
    locator (str): Where the physical copy sits, as one string. (pattern:
        ^(?:[A-Z]{2}-)?(?:AISLE|BAY|SHELF)-[0-9]{1,3}(?:\.[0-9]{1,2})?(?:-(?:LEFT|RIGHT|CENTRE))?(?:/[A-Za-z0-9_]{1,16})*$)
"""


def read_shelf_slot(source: Any) -> ShelfSlot:
    """Check a decoded `ShelfSlot` against the document, and hand it back as it arrived.

    Lenient; see `models`.
    """
    values = as_dict(source)
    require(values, 'ShelfSlot', ('position', 'book'))
    if 'book' in values:
        read_book(values['book'])
    return cast(ShelfSlot, values)
