# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from .shelf_slot import ShelfSlot

Shelf = list[ShelfSlot]
"""An array whose items are declared inline rather than by name."""
