#%RAML 1.0 Library
types:
  NoFacets: {}
  HasProperties:
    properties:
      a: string
  HasItems:
    items: string
  FromExplicitType:
    type: integer
  PropertyShorthand:
    properties:
      inferred:
        properties:
          nested: string
  AnnotatedScalar:
    type: string
    displayName: plain string
