# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Address:
    r"""Where a physical thing is sent.

    Attributes:
        line1 (str)
        city (str)
        postcode (str): (pattern: ^[A-Z0-9 ]{4,10}$)
        country (str): An ISO 3166-1 alpha-2 code. (minLength: 2, maxLength: 2)
        line2 (str)
    """

    line1: str
    city: str
    postcode: str
    country: str
    line2: str | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['line1'] = self.line1
        out['city'] = self.city
        out['postcode'] = self.postcode
        out['country'] = self.country
        if not isinstance(self.line2, Unset):
            out['line2'] = self.line2
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Address:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        line1 = values.get('line1', UNSET)
        city = values.get('city', UNSET)
        postcode = values.get('postcode', UNSET)
        country = values.get('country', UNSET)
        line2 = values.get('line2', UNSET)
        return cls(
            line1=line1 if not isinstance(line1, Unset) else absent('Address', 'line1'),
            city=city if not isinstance(city, Unset) else absent('Address', 'city'),
            postcode=postcode if not isinstance(postcode, Unset) else absent('Address', 'postcode'),
            country=country if not isinstance(country, Unset) else absent('Address', 'country'),
            line2=line2 if not isinstance(line2, Unset) else UNSET,
        )
