# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Amount:
    r"""A sum of money, in the smallest unit of its currency.

    Attributes:
        minor (int): Pence, cents, or the equivalent.
        currency (Literal['USD', 'EUR', 'GBP'])
    """

    minor: int
    currency: Literal['USD', 'EUR', 'GBP']

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['minor'] = self.minor
        out['currency'] = self.currency
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Amount:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        minor = values.get('minor', UNSET)
        currency = values.get('currency', UNSET)
        return cls(
            minor=minor if not isinstance(minor, Unset) else absent('Amount', 'minor'),
            currency=currency if not isinstance(currency, Unset) else absent('Amount', 'currency'),
        )
