# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Line:
    r"""Line

    Attributes:
        description (str)
        amount (float)
    """

    description: str
    amount: float

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['description'] = self.description
        out['amount'] = self.amount
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Line:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        description = values.get('description', UNSET)
        amount = values.get('amount', UNSET)
        return cls(
            description=description if not isinstance(description, Unset) else absent('Line', 'description'),
            amount=amount if not isinstance(amount, Unset) else absent('Line', 'amount'),
        )
