# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Money:
    r"""An amount and the currency it is denominated in.

    Attributes:
        amount (float): (minimum: 0, multipleOf: 0.01)
        currency (Literal['USD', 'EUR', 'GBP'])
    """

    amount: float
    currency: Literal['USD', 'EUR', 'GBP']

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['amount'] = self.amount
        out['currency'] = self.currency
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Money:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        amount = values.get('amount', UNSET)
        currency = values.get('currency', UNSET)
        return cls(
            amount=amount if not isinstance(amount, Unset) else absent('Money', 'amount'),
            currency=currency if not isinstance(currency, Unset) else absent('Money', 'currency'),
        )
