# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any

from ..types import UNSET, Unset, absent


@dataclass(slots=True)
class Page:
    r"""The envelope every paged collection is returned in.

    `total` counts the whole collection, not the page.

    Attributes:
        total (int)
        offset (int)
        limit (int)
    """

    total: int
    offset: int
    limit: int

    def to_dict(self) -> dict[str, Any]:
        """This value, as the JSON the document describes."""
        out: dict[str, Any] = {}
        out['total'] = self.total
        out['offset'] = self.offset
        out['limit'] = self.limit
        return out

    @classmethod
    def from_dict(cls, source: Mapping[str, Any]) -> Page:
        """Read one of these out of a decoded JSON body. Lenient; see `models`."""
        values = source if isinstance(source, Mapping) else {}
        total = values.get('total', UNSET)
        offset = values.get('offset', UNSET)
        limit = values.get('limit', UNSET)
        return cls(
            total=total if not isinstance(total, Unset) else absent('Page', 'total'),
            offset=offset if not isinstance(offset, Unset) else absent('Page', 'offset'),
            limit=limit if not isinstance(limit, Unset) else absent('Page', 'limit'),
        )
