# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from .book import Book
from .review import Review

Payload = list[Book] | Review
"""A union whose members are an array and an object, to show both."""
