# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

Tolerance = float
"""The bounds a scale is allowed to be out by, written at the limits of a 64-bit float because that is where a reader finds out whether the documentation survived the trip."""
