"""Turn a plan and a set of templates into a client package.

**The runtime is copied.** `client.py`, `types.py` and `errors.py` are ordinary
Python under `runtime/`, and they arrive in the generated package byte for byte.
The test suite runs them and a reader can read them. A template that produced
them instead would be a file nothing could check.

The import block is computed rather than formatted; `targets/shared/imports.py`
says why.
"""

from __future__ import annotations

import pathlib
from dataclasses import replace
from functools import partial
from typing import TYPE_CHECKING, Final

from ....naming import Names
from ....targets import Generated, Settings
from ..shared import docs
from ..shared.annotate import fill
from ..shared.imports import Needs, Source, imports_for
from ..shared.plan import Reserved, plan
from ..shared.templating import template_environment
from .annotate import CHECKS, make_annotator, reader

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping

    import jinja2

    from ....reader import Tree
    from ..shared.annotate import Annotation
    from ..shared.imports import Imports
    from ..shared.plan import Endpoint, Field, Model

__all__ = ['generate_httpx']

_HERE = pathlib.Path(__file__).resolve().parent
_TEMPLATES = _HERE / 'templates'
_RUNTIME = _HERE / 'runtime'

HEADER = '# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.'

#: The modules the generated package root already uses, so no declared type may
#: be given one of their names.
_RESERVED = Reserved(modules=frozenset({'types', 'client', 'errors'}))


def generate_httpx(tree: Tree, settings: Settings) -> Generated:
    """The whole package, as paths to text."""
    readers = Names()
    package = plan(tree, settings, partial(make_annotator, readers=readers), _RESERVED)
    environment = _environment()
    files: dict[str, str] = {}
    root = package.module

    files[f'{root}/__init__.py'] = environment.get_template('package_init.py.jinja').render(
        header=HEADER, package=package
    )
    files[f'{root}/py.typed'] = ''
    for name in ('types.py', 'errors.py', 'client.py'):
        files[f'{root}/{name}'] = f'{HEADER}\n{(_RUNTIME / name).read_text(encoding="utf-8")}'

    by_name = {model.name: model for model in package.models}
    checked = {model.name: reader(readers, model.name) for model in package.models if not model.is_alias}
    files[f'{root}/models/__init__.py'] = environment.get_template('models_init.py.jinja').render(
        header=HEADER,
        package=package,
        readers=checked,
        exported=sorted([*by_name, *checked.values()]),
    )
    for model in package.models:
        if model.is_alias:
            files[f'{root}/models/{model.module}.py'] = _alias(environment, model, by_name)
        else:
            files[f'{root}/models/{model.module}.py'] = _model(environment, model, by_name, readers)

    files[f'{root}/api/__init__.py'] = environment.get_template('api_init.py.jinja').render(
        header=HEADER, package=package
    )
    for group in package.groups:
        endpoints = package.in_group(group)
        files[f'{root}/api/{group}/__init__.py'] = environment.get_template('group_init.py.jinja').render(
            header=HEADER, group=group, endpoints=endpoints
        )
        for endpoint in endpoints:
            files[f'{root}/api/{group}/{endpoint.module}.py'] = _endpoint(environment, endpoint, by_name, readers)

    files[f'{root}/security.py'] = environment.get_template('security.py.jinja').render(header=HEADER, package=package)
    files['pyproject.toml'] = environment.get_template('pyproject.toml.jinja').render(package=package)
    files['README.md'] = environment.get_template('README.md.jinja').render(package=package)

    return Generated(package=package.distribution, files=files)


# -- assembling ----------------------------------------------------------------


def _alias(environment: jinja2.Environment, model: Model, by_name: Mapping[str, Model]) -> str:
    """A bare assignment, with no reader of its own.

    It still *names* the models it is built from, so those are imported; it
    checks nothing, so what a check calls is not.
    """
    annotations = [_spelled(one) for one in model.annotations]
    return environment.get_template('model.py.jinja').render(
        header=HEADER,
        model=model,
        imports=_imports_for(annotations, by_name, Needs(own=model.name)),
    )


def _model(environment: jinja2.Environment, model: Model, by_name: Mapping[str, Model], readers: Names) -> str:
    keys = [(one, _key(model, one)) for one in model.fields]
    required = [one.wire for one in model.fields if one.required]
    needs = Needs(
        names=(
            'Any',
            'TypedDict',
            'cast',
            *(('NotRequired',) if len(required) < len(model.fields) else ()),
            *(('Literal',) if model.discriminator else ()),
        ),
        runtime=('as_dict', 'require') if required else ('as_dict',),
        own=model.name,
        beside=_readers(model.annotations, readers),
    )
    return environment.get_template('model.py.jinja').render(
        header=HEADER,
        model=model,
        keys=keys,
        required=required,
        reader=reader(readers, model.name),
        imports=_imports_for(model.annotations, by_name, needs),
    )


def _key(model: Model, one: Field) -> str:
    """The type one key holds, before `NotRequired` is wrapped round it.

    Where the document states the value that means this type, the discriminator
    is that value's `Literal`, so a type checker narrows a union on it.
    """
    if model.discriminator is not None and one.wire == model.discriminator[0]:
        return f'Literal[{model.discriminator[1]!r}]'
    return one.annotation.spelling


def _endpoint(environment: jinja2.Environment, endpoint: Endpoint, by_name: Mapping[str, Model], readers: Names) -> str:
    optional = any(not one.required for one in endpoint.arguments)
    clients = 'AuthenticatedClient, Client' if endpoint.optional_auth else _client_type(endpoint)
    # Only the answer is read; every other annotation is a spelling.
    answer = endpoint.success.annotation if endpoint.success else None
    annotations = [one if one is answer else _spelled(one) for one in endpoint.annotations]
    return environment.get_template('endpoint.py.jinja').render(
        header=HEADER,
        endpoint=endpoint,
        client_type=_client_type(endpoint),
        imports=_imports_for(
            annotations,
            by_name,
            Needs(
                names=('HTTPStatus', 'Any', 'httpx', *(('cast',) if answer else ())),
                lines=('from ... import errors', f'from ...client import {clients}'),
                # `UNSET` and `Unset` only where an argument is optional.
                runtime=('UNSET', 'Mismatch', 'Response', 'Unset', 'reading')
                if optional
                else ('Mismatch', 'Response', 'reading'),
                types_import='...types',
                model_prefix='...models.',
                beside=_readers([answer] if answer else [], readers),
            ),
        ),
    )


def _spelled(annotation: Annotation) -> Annotation:
    """An annotation whose check is not run here, so only its spelling is imported."""
    return replace(annotation, runtime=annotation.runtime - CHECKS)


def _readers(annotations: Iterable[Annotation], readers: Names) -> dict[str, tuple[str, ...]]:
    """The readers each model's module must hand over, where these checks call them."""
    return {name: (reader(readers, name),) for one in annotations for name in one.readers}


def _client_type(endpoint: Endpoint) -> str:
    """Which client a call needs, from what the document secured it with."""
    if endpoint.requires_auth:
        return 'AuthenticatedClient'
    return 'AuthenticatedClient | Client' if endpoint.optional_auth else 'Client'


def _environment() -> jinja2.Environment:
    environment = template_environment(_TEMPLATES)
    environment.filters['format_with'] = fill
    environment.filters['attribute'] = docs.attribute
    environment.filters['key'] = docs.key
    return environment


#: Where every name a generated module imports comes from. `module` is `None`
#: for a name that is imported as a module in its own right, and `third_party`
#: decides which block the import lands in.
_FROM: Final = {
    'datetime': Source(None, third_party=False),
    'httpx': Source(None, third_party=True),
    'Any': Source('typing', third_party=False),
    'Literal': Source('typing', third_party=False),
    'NotRequired': Source('typing', third_party=False),
    'TypedDict': Source('typing', third_party=False),
    'cast': Source('typing', third_party=False),
    'HTTPStatus': Source('http', third_party=False),
}


def _imports_for(annotations: Iterable[Annotation], by_name: Mapping[str, Model], needs: Needs) -> Imports:
    return imports_for(annotations, by_name, needs, _FROM)
