# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""The `securitySchemes:` this API declares, as credential mechanics.

Each `SchemeSpec` says which header carries the credential and what precedes it,
so a scheme that names its own header through `describedBy:` is read where the
caller is writing. Each route under `api/` depends on the ones its operation
accepts, and hands the implementation a `Credential`.

Verifying one is yours: the document says an operation is secured and which
scopes it narrows to, not what a valid token looks like.
"""

from __future__ import annotations

from .runtime import SchemeSpec

OAUTH2 = SchemeSpec(
    name='oauth2',
    type='OAuth 2.0',
    header_name='Authorization',
    prefix='Bearer',
    scopes=(
        'read:books',
        'write:books',
        'delete:books',
        'read:reviews',
        'write:reviews',
        'admin:catalogue',
    ),
)
"""Standard three-legged flow."""

MACHINE_TOKEN = SchemeSpec(
    name='machineToken',
    type='OAuth 2.0',
    header_name='Authorization',
    prefix='Bearer',
    scopes=(
        'read:books',
        'read:deliveries',
    ),
)
"""Two-legged client credentials, for server-to-server callers that have no user to send through a browser."""

BASIC = SchemeSpec(
    name='basic',
    type='Basic Authentication',
    header_name='Authorization',
    prefix='Basic',
)
"""Username and password, for server-to-server callers only."""

SCHEMES: dict[str, SchemeSpec] = {
    'oauth2': OAUTH2,
    'machineToken': MACHINE_TOKEN,
    'basic': BASIC,
}
"""Every scheme, by the name the document gave it."""

__all__ = [
    'BASIC',
    'MACHINE_TOKEN',
    'OAUTH2',
    'SCHEMES',
]
