# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import abc
from http import HTTPStatus
from typing import Annotated

from fastapi import APIRouter, Depends, Response
from pydantic import Field

from .. import security
from ..models.book import Book
from ..runtime import Credential, Responses, accepts, requires

POST_BOOKS = Responses({
    HTTPStatus.CREATED: 'Created',
    HTTPStatus.BAD_REQUEST: 'The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.',
})
"""What `POST /books` documents, and what the document calls each.

    raise POST_BOOKS.fail(400)

A status this does not name raises `LookupError` where you wrote it, rather
than answering a caller with something the document never described.
"""

GET_BOOKS = Responses({
    HTTPStatus.OK: 'OK',
})
"""What `GET /books` documents, and what the document calls each.

    raise GET_BOOKS.fail(200)

A status this does not name raises `LookupError` where you wrote it, rather
than answering a caller with something the document never described.
"""

GET_BOOKS_ISBN = Responses({
    HTTPStatus.OK: 'OK',
})
"""What `GET /books/{isbn}` documents, and what the document calls each.

    raise GET_BOOKS_ISBN.fail(200)

A status this does not name raises `LookupError` where you wrote it, rather
than answering a caller with something the document never described.
"""

DELETE_BOOKS_ISBN = Responses({
    HTTPStatus.NO_CONTENT: 'No Content',
})
"""What `DELETE /books/{isbn}` documents, and what the document calls each.

    raise DELETE_BOOKS_ISBN.fail(204)

A status this does not name raises `LookupError` where you wrote it, rather
than answering a caller with something the document never described.
"""


class BooksApi(abc.ABC):
    """The `books` operations, as the methods to implement.

    `Api` joins this with the other groups; subclass that rather than this, so
    that one object answers the whole document.
    """

    @abc.abstractmethod
    async def post_books(
        self,
        *,
        body: Book,
        credential: Credential,
        response: Response,
    ) -> Book:
        r"""Add a book

        Adds one book to the catalogue and returns it with its identifier.

        Args:
            body (Book): sent as application/json.
            credential (Credential): the credential the caller sent.
            response (Response): set Location on it; the document says this carries it.

        Responses:
            201: Created
            400: The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.

        Returns:
            Book -- the 201 response.
        """

    @abc.abstractmethod
    async def get_books(
        self,
        *,
        credential: Credential,
        offset: int = 0,
        limit: Annotated[int, Field(le=100)] = 20,
    ) -> list[Book]:
        r"""List Books

        Returns a page of Book records.

        Args:
            credential (Credential): the credential the caller sent.
            offset (int): Default: 0.
            limit (int): (maximum: 100) Default: 20.

        Responses:
            200

        Returns:
            list[Book] -- the 200 response.
        """

    @abc.abstractmethod
    async def get_books_isbn(
        self,
        *,
        isbn: Annotated[str, Field(pattern=r'^\d{13}$')],
        credential: Credential | None,
    ) -> Book:
        r"""Retrieve a book

        Returns one book by its ISBN-13.

        Args:
            isbn (str): (pattern: ^\d{13}$)
            credential (Credential | None): the credential the caller sent, if any.

        Responses:
            200

        Returns:
            Book -- the 200 response.
        """

    @abc.abstractmethod
    async def delete_books_isbn(
        self,
        *,
        isbn: Annotated[str, Field(pattern=r'^\d{13}$')],
        credential: Credential,
    ) -> None:
        r"""Delete a book

        Idempotent.

        Args:
            isbn (str): (pattern: ^\d{13}$)
            credential (Credential): the credential the caller sent.

        Responses:
            204

        Returns:
            None -- the 204 response.
        """


def router(implementation: BooksApi) -> APIRouter:
    """Bind one implementation to the routes the document describes.

    Every constraint the document states is on the route rather than in the
    method: a request that does not match is a 422 before the implementation is
    called at all.
    """
    api = APIRouter(tags=['books'])

    @api.post(
        '/books',
        status_code=201,
        summary='Add a book',
        description='Adds one book to the catalogue and returns it with its identifier.',
        responses={201: {'description': 'Created', 'headers': {'Location': {'required': True, 'schema': {'type': 'string'}}}}, 400: {'description': 'The body did not match `Book` — see the schema above. The response carries no envelope; the status code is the whole of it.'}},
    )
    async def post_books(
        body: Book,
        credential: Annotated[Credential, Depends(requires(security.OAUTH2, security.BASIC, scopes=('write:books', 'read:reviews', 'write:reviews', 'admin:catalogue')))],
        response: Response,
    ) -> Book:
        return await implementation.post_books(
            body=body,
            credential=credential,
            response=response,
        )

    @api.get(
        '/books',
        status_code=200,
        summary='List Books',
        description='Returns a page of Book records.',
    )
    async def get_books(
        credential: Annotated[Credential, Depends(requires(security.OAUTH2))],
        offset: int = 0,
        limit: Annotated[int, Field(le=100)] = 20,
    ) -> list[Book]:
        return await implementation.get_books(
            credential=credential,
            offset=offset,
            limit=limit,
        )

    @api.get(
        '/books/{isbn}',
        status_code=200,
        summary='Retrieve a book',
        description='Returns one book by its ISBN-13.',
    )
    async def get_books_isbn(
        isbn: Annotated[str, Field(pattern=r'^\d{13}$')],
        credential: Annotated[Credential | None, Depends(accepts(security.OAUTH2, scopes=('read:books',)))],
    ) -> Book:
        return await implementation.get_books_isbn(
            isbn=isbn,
            credential=credential,
        )

    @api.delete(
        '/books/{isbn}',
        status_code=204,
        response_class=Response,
        summary='Delete a book',
        description='Removes a book from the catalogue. Idempotent.',
    )
    async def delete_books_isbn(
        isbn: Annotated[str, Field(pattern=r'^\d{13}$')],
        credential: Annotated[Credential, Depends(requires(security.OAUTH2, scopes=('write:books',)))],
    ) -> None:
        return await implementation.delete_books_isbn(
            isbn=isbn,
            credential=credential,
        )

    return api
