# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import abc
import datetime
from typing import Annotated, Literal

from fastapi import APIRouter, Depends, Query

from .. import security
from ..models.delivery import Delivery
from ..runtime import Credential, requires


class DeliveriesApi(abc.ABC):
    """The `deliveries` operations, as the methods to implement.

    `Api` joins this with the other groups; subclass that rather than this, so
    that one object answers the whole document.
    """

    @abc.abstractmethod
    async def get_deliveries(
        self,
        *,
        credential: Credential,
        since: datetime.datetime,
        status: Literal['pending', 'sent', 'delivered'] | None = None,
        city: str | None = None,
        carrier: Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon', 'evri-standard'] | None = None,
    ) -> list[Delivery]:
        r"""List deliveries

        Every delivery, newest first.

        Args:
            credential (Credential): the credential the caller sent.
            since (datetime.datetime): Only deliveries promised on or after this instant.
            status (Literal['pending', 'sent', 'delivered'] | None)
            city (str | None): Matched against the address, case-insensitively.
            carrier (Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon',
                'evri-standard'] | None): Only deliveries handed to this carrier.

        Responses:
            200

        Returns:
            list[Delivery] -- the 200 response.
        """


def router(implementation: DeliveriesApi) -> APIRouter:
    """Bind one implementation to the routes the document describes.

    Every constraint the document states is on the route rather than in the
    method: a request that does not match is a 422 before the implementation is
    called at all.
    """
    api = APIRouter(tags=['deliveries'])

    @api.get(
        '/deliveries',
        status_code=200,
        summary='List deliveries',
        description='Every delivery, newest first.',
    )
    async def get_deliveries(
        credential: Annotated[Credential, Depends(requires(security.MACHINE_TOKEN, security.OAUTH2, scopes=('read:deliveries', 'read:books')))],
        since: Annotated[datetime.datetime, Query(description='Only deliveries promised on or after this instant.')],
        status: Literal['pending', 'sent', 'delivered'] | None = None,
        city: Annotated[str | None, Query(description='Matched against the address, case-insensitively.')] = None,
        carrier: Annotated[Literal['royal-mail-tracked-48-signed-for', 'dpd-next-day-before-noon', 'evri-standard'] | None, Query(description='Only deliveries handed to this carrier.')] = None,
    ) -> list[Delivery]:
        return await implementation.get_deliveries(
            credential=credential,
            since=since,
            status=status,
            city=city,
            carrier=carrier,
        )

    return api
