# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import abc
from typing import Annotated

from fastapi import APIRouter, Depends

from .. import security
from ..models.publication import Publication
from ..runtime import Credential, requires


class PublicationsApi(abc.ABC):
    """The `publications` operations, as the methods to implement.

    `Api` joins this with the other groups; subclass that rather than this, so
    that one object answers the whole document.
    """

    @abc.abstractmethod
    async def get_publications(
        self,
        *,
        credential: Credential,
    ) -> list[Publication]:
        r"""List publications

        Every publication, of whatever kind.

        Args:
            credential (Credential): the credential the caller sent.

        Responses:
            200

        Returns:
            list[Publication] -- the 200 response.
        """


def router(implementation: PublicationsApi) -> APIRouter:
    """Bind one implementation to the routes the document describes.

    Every constraint the document states is on the route rather than in the
    method: a request that does not match is a 422 before the implementation is
    called at all.
    """
    api = APIRouter(tags=['publications'])

    @api.get(
        '/publications',
        status_code=200,
        summary='List publications',
        description='Every publication, of whatever kind.',
    )
    async def get_publications(
        credential: Annotated[Credential, Depends(requires(security.OAUTH2))],
    ) -> list[Publication]:
        return await implementation.get_publications(
            credential=credential,
        )

    return api
