# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import abc
from http import HTTPStatus
from typing import Annotated

from fastapi import APIRouter, Depends, Query
from pydantic import Field

from .. import security
from ..models.book import Book
from ..runtime import Credential, Responses, requires

GET_SEARCH = Responses({
    HTTPStatus.OK: 'OK',
})
"""What `GET /search` documents, and what the document calls each.

    raise GET_SEARCH.fail(200)

A status this does not name raises `LookupError` where you wrote it, rather
than answering a caller with something the document never described.
"""


class SearchApi(abc.ABC):
    """The `search` operations, as the methods to implement.

    `Api` joins this with the other groups; subclass that rather than this, so
    that one object answers the whole document.
    """

    @abc.abstractmethod
    async def get_search(
        self,
        *,
        credential: Credential,
        q: str | float,
        sort: Annotated[str, Field(pattern=r'^-?(title|isbn|price)$')] = 'title',
    ) -> list[Book]:
        r"""Search the catalogue

        Full-text search across titles and authors.

        Args:
            credential (Credential): the credential the caller sent.
            q (str | float): The words to search for. Quoted phrases are matched whole.
            sort (str): A field name, optionally prefixed with `-` to reverse it. (pattern:
                ^-?(title|isbn|price)$) Default: 'title'.

        Responses:
            200

        Returns:
            list[Book] -- the 200 response.
        """


def router(implementation: SearchApi) -> APIRouter:
    """Bind one implementation to the routes the document describes.

    Every constraint the document states is on the route rather than in the
    method: a request that does not match is a 422 before the implementation is
    called at all.
    """
    api = APIRouter(tags=['search'])

    @api.get(
        '/search',
        status_code=200,
        summary='Search the catalogue',
        description='Full-text search across titles and authors.',
    )
    async def get_search(
        credential: Annotated[Credential, Depends(requires(security.OAUTH2))],
        q: Annotated[str | float, Query(description='The words to search for. Quoted phrases are matched whole.')],
        sort: Annotated[Annotated[str, Field(pattern=r'^-?(title|isbn|price)$')], Query(description='A field name, optionally prefixed with `-` to reverse it.')] = 'title',
    ) -> list[Book]:
        return await implementation.get_search(
            credential=credential,
            q=q,
            sort=sort,
        )

    return api
