# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import abc
from typing import Annotated

from fastapi import APIRouter, Depends
from pydantic import Field

from .. import security
from ..models.book import Book
from ..models.review import Review
from ..models.shelf_slot import ShelfSlot
from ..runtime import Credential, requires


class ShelvesApi(abc.ABC):
    """The `shelves` operations, as the methods to implement.

    `Api` joins this with the other groups; subclass that rather than this, so
    that one object answers the whole document.
    """

    @abc.abstractmethod
    async def post_shelves(
        self,
        *,
        body: list[Book] | Review,
        credential: Credential,
    ) -> Annotated[list[ShelfSlot], Field(min_length=1)]:
        r"""Create a shelf

        Accepts either a list of books or a single review.

        Args:
            body (list[Book] | Review): sent as application/json.
            credential (Credential): the credential the caller sent.

        Responses:
            201: Created
            422: The payload matched neither member of the union.
            500: Something went wrong on our side.

        Returns:
            Annotated[list[ShelfSlot], Field(min_length=1)] -- the 201 response.
        """


def router(implementation: ShelvesApi) -> APIRouter:
    """Bind one implementation to the routes the document describes.

    Every constraint the document states is on the route rather than in the
    method: a request that does not match is a 422 before the implementation is
    called at all.
    """
    api = APIRouter(tags=['shelves'])

    @api.post(
        '/shelves',
        status_code=201,
        summary='Create a shelf',
        description='Accepts either a list of books or a single review.',
        responses={422: {'description': 'The payload matched neither member of the union.'}, 500: {'description': 'Something went wrong on our side.'}},
    )
    async def post_shelves(
        body: list[Book] | Review,
        credential: Annotated[Credential, Depends(requires(security.OAUTH2))],
    ) -> Annotated[list[ShelfSlot], Field(min_length=1)]:
        return await implementation.post_shelves(
            body=body,
            credential=credential,
        )

    return api
