# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
"""Every type the document declares, and every one its operations reach.

**The models are flat.** RAML inheritance has no pydantic subclass form -- `type:
[A, B]` has no MRO and a narrowed property has no override -- so `Magazine` is
not a subclass of `Publication`: it carries its supertype's properties and is a
class of its own. Where the document states a `discriminatorValue:`, the module
holds it as `DISCRIMINATOR`, and the property that carries it is a `Literal` of
that value.

Every facet the document states is enforced. A `minLength:`, a `pattern:` or a
`maximum:` is a pydantic constraint, so a request that does not match is a 422
before any handler runs. Two are not: `multipleOf:`, which pydantic compares in
binary floating point, and the document's `default:` for a *property*, which is
carried as the attribute's default only where the type states one.
"""

from __future__ import annotations

from .address import Address
from .amount import Amount
from .anything import Anything
from .author import Author
from .barcode import Barcode
from .book import Book
from .chain import Chain
from .delivery import Delivery
from .delivery_query import DeliveryQuery
from .entity import Entity
from .grams import Grams
from .invoice import Invoice
from .isbn import Isbn
from .line import Line
from .magazine import Magazine
from .money import Money
from .page import Page
from .paged import Paged
from .pamphlet import Pamphlet
from .parcel import Parcel
from .payload import Payload
from .prices import Prices
from .publication import Publication
from .review import Review
from .search import Search
from .shelf import Shelf
from .shelf_slot import ShelfSlot
from .tolerance import Tolerance

__all__ = [
    'Address',
    'Amount',
    'Anything',
    'Author',
    'Barcode',
    'Book',
    'Chain',
    'Delivery',
    'DeliveryQuery',
    'Entity',
    'Grams',
    'Invoice',
    'Isbn',
    'Line',
    'Magazine',
    'Money',
    'Page',
    'Paged',
    'Pamphlet',
    'Parcel',
    'Payload',
    'Prices',
    'Publication',
    'Review',
    'Search',
    'Shelf',
    'ShelfSlot',
    'Tolerance',
]
