# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Address(BaseModel):
    r"""Where a physical thing is sent.

    Attributes:
        line1 (str)
        city (str)
        postcode (str): (pattern: ^[A-Z0-9 ]{4,10}$)
        country (str): An ISO 3166-1 alpha-2 code. (minLength: 2, maxLength: 2)
        line2 (str | None)
    """

    model_config = ConfigDict(populate_by_name=True)

    line1: str
    city: str
    postcode: Annotated[str, Field(pattern=r'^[A-Z0-9 ]{4,10}$')]
    country: Annotated[str, Field(min_length=2, max_length=2)]
    line2: str | None = None
