# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class Amount(BaseModel):
    r"""A sum of money, in the smallest unit of its currency.

    Attributes:
        minor (int): Pence, cents, or the equivalent.
        currency (Literal['USD', 'EUR', 'GBP'])
    """

    model_config = ConfigDict(populate_by_name=True)

    minor: int
    currency: Literal['USD', 'EUR', 'GBP']
