# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Author(BaseModel):
    r"""Author

    Attributes:
        name (str)
        verified (bool): Default: False.
    """

    model_config = ConfigDict(populate_by_name=True)

    name: str
    verified: bool
