# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Barcode(BaseModel):
    r"""Barcode

    Attributes:
        symbology (Literal['EAN-13', 'UPC-A', 'CODE-128'])
        code (str): (minLength: 1)
    """

    model_config = ConfigDict(populate_by_name=True)

    symbology: Literal['EAN-13', 'UPC-A', 'CODE-128']
    code: Annotated[str, Field(min_length=1)]
