# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from .address import Address
from .parcel import Parcel


class Delivery(BaseModel):
    r"""Where an order goes, and when it was promised.

    Attributes:
        address (Address): Where a physical thing is sent.
        promised_for (datetime.datetime)
        parcel (Parcel | None): What a delivery is packed in.
    """

    model_config = ConfigDict(populate_by_name=True)

    address: Address
    promised_for: Annotated[datetime.datetime, Field(alias='promisedFor')]
    parcel: Parcel | None = None
