# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

import datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Entity(BaseModel):
    r"""Entity

    Attributes:
        id_ (str)
        created_at (datetime.datetime)
    """

    model_config = ConfigDict(populate_by_name=True)

    id_: Annotated[str, Field(alias='id')]
    created_at: Annotated[datetime.datetime, Field(alias='createdAt')]
