# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from .amount import Amount
from .line import Line


class Invoice(BaseModel):
    r"""A type declared by JSON Schema rather than by RAML.

    Attributes:
        number (str): The invoice number, as printed. (pattern: ^INV-[0-9]{6}$)
        total (float): The amount due, in the currency of the account. (minimum: 0, multipleOf:
            0.01)
        settled (Amount | None): A sum of money, in the smallest unit of its currency.
        paid (bool): Default: False.
        lines (list[Line] | None): (minItems: 1)
    """

    model_config = ConfigDict(populate_by_name=True)

    number: Annotated[str, Field(pattern=r'^INV-[0-9]{6}$')]
    total: Annotated[float, Field(ge=0)]
    settled: Amount | None = None
    paid: bool = False
    lines: Annotated[list[Line], Field(min_length=1)] | None = None
