# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Line(BaseModel):
    r"""Line

    Attributes:
        description (str)
        amount (float)
    """

    model_config = ConfigDict(populate_by_name=True)

    description: str
    amount: float
