# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict

DISCRIMINATOR = ('kind', 'monthly')
"""The property this type is told apart by, and the value that means this type.

Models are flat, so switch on this where you would otherwise use `isinstance`.
The attribute itself is a `Literal` of that value, which is what lets a union
over this type and its siblings be tagged.
"""


class Magazine(BaseModel):
    r"""A periodical, told apart by `kind: monthly`.

    Attributes:
        issue (int)
        kind (Literal['monthly'])
        title (str)
    """

    model_config = ConfigDict(populate_by_name=True)

    issue: int
    kind: Literal['monthly']
    title: str
