# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Money(BaseModel):
    r"""An amount and the currency it is denominated in.

    Attributes:
        amount (float): (minimum: 0, multipleOf: 0.01)
        currency (Literal['USD', 'EUR', 'GBP'])
    """

    model_config = ConfigDict(populate_by_name=True)

    amount: Annotated[float, Field(ge=0)]
    currency: Literal['USD', 'EUR', 'GBP']
