# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Page(BaseModel):
    r"""The envelope every paged collection is returned in.

    `total` counts the whole collection, not the page.

    Attributes:
        total (int)
        offset (int)
        limit (int)
    """

    model_config = ConfigDict(populate_by_name=True)

    total: int
    offset: int
    limit: int
