# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Parcel(BaseModel):
    r"""What a delivery is packed in.

    Attributes:
        weight (int): Whole grams. Nothing here is sold by fractions of one. (minimum: 1, maximum:
            9223372036854775807)
        tracking_number (int): The carrier's own identifier, which is a signed 64-bit integer.
        tolerance (float | None): The bounds a scale is allowed to be out by, written at the limits
            of a 64-bit float because that is where a reader finds out whether the documentation
            survived the trip. (minimum: 2.2250738585072014E-308, maximum: 1.7976931348623157E+308,
            multipleOf: 0.000001)
    """

    model_config = ConfigDict(populate_by_name=True)

    weight: Annotated[int, Field(ge=1, le=9223372036854775807)]
    tracking_number: Annotated[int, Field(alias='trackingNumber')]
    tolerance: Annotated[float, Field(ge=2.2250738585072014E-308, le=1.7976931348623157E+308)] | None = None
