# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Publication(BaseModel):
    r"""Everything the store sells.

    The `kind` property says which.

    Attributes:
        kind (str)
        title (str)
    """

    model_config = ConfigDict(populate_by_name=True)

    kind: str
    title: str
