# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from typing import Annotated

from pydantic import Field

Tolerance = Annotated[float, Field(ge=2.2250738585072014E-308, le=1.7976931348623157E+308)]
"""The bounds a scale is allowed to be out by, written at the limits of a 64-bit float because that is where a reader finds out whether the documentation survived the trip."""
