# Generated by raml-codegen from a RAML 1.0 definition. Do not edit.
from __future__ import annotations

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient
from ...models.book import Book
from ...models.review import Review
from ...models.shelf_slot import ShelfSlot
from ...types import Mismatch, Response, as_list, reading, to_json

PATH = '/shelves'
"""The path this module calls, before its `{...}` tokens are filled in."""

METHOD = 'post'
"""The HTTP method this module uses."""

SCHEMES = ('oauth2',)
"""The `securedBy:` schemes this operation accepts.

`security.py` holds the mechanics of each: which header carries the credential,
and what precedes it.
"""


def _kwargs(
    *,
    body: list[Book] | Review,
) -> dict[str, Any]:
    path = PATH

    params: dict[str, Any] = {}

    headers: dict[str, str] = {}
    headers['Content-Type'] = 'application/json'

    out: dict[str, Any] = {'method': METHOD, 'url': path}
    if params:
        out['params'] = params
    if headers:
        out['headers'] = headers
    out['json'] = to_json(body)
    return out


def _parse(*, client: AuthenticatedClient, response: httpx.Response) -> list[ShelfSlot] | None:
    if response.status_code == 201:
        payload = response.json()
        return [ShelfSlot.from_dict(_item) for _item in as_list(payload)]
    if response.status_code in {422, 500}:
        # Documented, and either carries no body or is not the one `sync`
        # answers with. The raw response is on the detailed variants.
        return None
    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    return None


def _build(*, client: AuthenticatedClient, response: httpx.Response) -> Response[list[ShelfSlot]]:
    """The response, and whatever could be made of its body.

    Nothing a *payload* does gets out of here. A body that is not what the
    document describes -- a missing property, an unreadable date, HTML where
    JSON was promised -- lands in `mismatches`, and `content` still holds the
    bytes. Only `errors.UnexpectedStatus`, which the caller asked for, and a
    transport error, which is not about the payload, travel further.
    """
    parsed: list[ShelfSlot] | None = None
    with reading(strict=client.strict) as mismatches:
        try:
            parsed = _parse(client=client, response=response)
        except errors.ClientError:
            raise
        except Exception as unreadable:  # noqa: BLE001 - a payload may be anything at all
            mismatches.append(Mismatch('list[ShelfSlot]', '', f'{type(unreadable).__name__}: {unreadable}'))
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=parsed,
        mismatches=tuple(mismatches),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: list[Book] | Review,
) -> Response[list[ShelfSlot]]:
    r"""Create a shelf

    Accepts either a list of books or a single review.

    Args:
        body (list[Book] | Review): sent as application/json.

    Responses:
        201: Created
        422: The payload matched neither member of the union.
        500: Something went wrong on our side.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[list[ShelfSlot]] -- the status, the raw content and the parsed body.
    """

    response = client.get_httpx_client().request(**_kwargs(
        body=body,
    ))
    return _build(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: list[Book] | Review,
) -> list[ShelfSlot] | None:
    r"""Create a shelf

    Accepts either a list of books or a single review.

    Args:
        body (list[Book] | Review): sent as application/json.

    Responses:
        201: Created
        422: The payload matched neither member of the union.
        500: Something went wrong on our side.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        list[ShelfSlot] -- the parsed body of the 201 response, or None.
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: list[Book] | Review,
) -> Response[list[ShelfSlot]]:
    r"""Create a shelf

    Accepts either a list of books or a single review.

    Args:
        body (list[Book] | Review): sent as application/json.

    Responses:
        201: Created
        422: The payload matched neither member of the union.
        500: Something went wrong on our side.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        Response[list[ShelfSlot]] -- the status, the raw content and the parsed body.
    """

    response = await client.get_async_httpx_client().request(**_kwargs(
        body=body,
    ))
    return _build(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: list[Book] | Review,
) -> list[ShelfSlot] | None:
    r"""Create a shelf

    Accepts either a list of books or a single review.

    Args:
        body (list[Book] | Review): sent as application/json.

    Responses:
        201: Created
        422: The payload matched neither member of the union.
        500: Something went wrong on our side.

    Raises:
        errors.UnexpectedStatus: the server answered with an undocumented status
            and the client was built with raise_on_unexpected_status.
        httpx.TimeoutException: the request took longer than client.timeout.

    Returns:
        list[ShelfSlot] -- the parsed body of the 201 response, or None.
    """

    return (
        await asyncio_detailed(
        client=client,
        body=body,
        )
    ).parsed
